<a href="https://colab.research.google.com/github/gertdreyer/MIT808-standard-deviants/blob/main/MIT808_Data_Retrieval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install Dependencies

In [ ]:
!pip install boto3

!pip install pyiceberg[hive] pandas pyarrow

Collecting boto3
  Downloading boto3-1.42.68-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.43.0,>=1.42.68 (from boto3)
  Downloading botocore-1.42.68-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<1.43.0,>=1.42.68->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.43.0,>=1.42.68->boto3) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.68->boto3) (1.17.0)
Downloading boto3-1.42.68-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 7.6 MB/s eta 0:00:00
Downloading botocore-1.42.68-py3-none-any.whl (14.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 116.4 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 9.8 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.42.68 botocore-1.42.68 jmespath-1.1.0 s3transfer-0.16.0
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: pyiceberg[hive] in /usr/local/lib/python3.12/dist-packages (0.11.1)
Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (5.2.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (2.32.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (8.3.1)
Requirement already satisfied: rich<15.0.0,>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (13.9.4)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (1.7.3)
Requirement already satisfied: pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (2.12.3)
Requirement already satisfied: fsspec>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (2025.3.0)
Requirement already satisfied: pyparsing<4.0.0,>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (3.3.2)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (1.0.3)
Requirement already satisfied: cachetools<7.0,>=5.5 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (6.2.6)
Requirement already satisfied: zstandard<1.0.0,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg[hive]) (0.25.0)
Collecting thrift<1.0.0,>=0.13.0 (from pyiceberg[hive])
  Downloading thrift-0.22.0.tar.gz (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 6.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0->pyiceberg[hive]) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0->pyiceberg[hive]) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0->pyiceberg[hive]) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.12.0,!=2.12.1,!=2.4.0,!=2.4.1,<3.0,>=2.0->pyiceberg[hive]) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg[hive]) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg[hive]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg[hive]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg[hive]) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg[hive]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg[hive]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=10.11.0->pyiceberg[hive]) (0.1.2)
Building wheels for collected packages: thrift
  Building wheel for thrift (setup.py) ... done
  Created wheel for thrift: filename=thrift-0.22.0-cp312-cp312-linux_x86_64.whl size=413530 sha256=4d8de1b83244945bf1aad84c05d1df5d8f3aea00fa3a77a0b64abc6fe81118d8
  Stored in directory: /root/.cache/pip/wheels/03/30/a2/6e53de46f9d8f098a6b7c4a57dbdcafa5f11e87274e139f50b
Successfully built thrift
Installing collected packages: thrift
Successfully installed thrift-0.22.0

In [ ]:


!pip install scrapling

Collecting markdownify
  Downloading markdownify-1.2.2-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: beautifulsoup4<5,>=4.9 in /usr/local/lib/python3.12/dist-packages (from markdownify) (4.13.5)
Requirement already satisfied: six<2,>=1.15 in /usr/local/lib/python3.12/dist-packages (from markdownify) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5,>=4.9->markdownify) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5,>=4.9->markdownify) (4.15.0)
Downloading markdownify-1.2.2-py3-none-any.whl (15 kB)
Installing collected packages: markdownify
Successfully installed markdownify-1.2.2
Collecting scrapling
  Downloading scrapling-0.4.2-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: lxml>=6.0.2 in /usr/local/lib/python3.12/dist-packages (from scrapling) (6.0.2)
Collecting cssselect>=1.4.0 (from scrapling)
  Downloading cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: orjson>=3.11.7 in /usr/local/lib/python3.12/dist-packages (from scrapling) (3.11.7)
Collecting tld>=0.13.2 (from scrapling)
  Downloading tld-0.13.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting w3lib>=2.4.0 (from scrapling)
  Downloading w3lib-2.4.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from scrapling) (4.15.0)
Downloading scrapling-0.4.2-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.5/116.5 kB 8.5 MB/s eta 0:00:00
Downloading cssselect-1.4.0-py3-none-any.whl (18 kB)
Downloading tld-0.13.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 24.5 MB/s eta 0:00:00
Downloading w3lib-2.4.0-py3-none-any.whl (21 kB)
Installing collected packages: w3lib, tld, cssselect, scrapling
Successfully installed cssselect-1.4.0 scrapling-0.4.2 tld-0.13.2 w3lib-2.4.0

In [ ]:
# set env
import os
from google.colab import userdata
os.environ['PYICEBERG_CATALOG__DEFAULT__S3__ACCESS_KEY_ID'] = userdata.get('PYICEBERG_CATALOG__DEFAULT__S3__ACCESS_KEY_ID')
os.environ['PYICEBERG_DOWNCAST_NS_TIMESTAMP_TO_US_ON_WRITE'] = 'true'
os.environ['PYICEBERG_CATALOG__DEFAULT__S3__SECRET_ACCESS_KEY'] = userdata.get('PYICEBERG_CATALOG__DEFAULT__S3__SECRET_ACCESS_KEY')

In [ ]:
from pyiceberg.catalog import load_catalog, rest
import pandas as pd
import pyarrow as pa
from datetime import datetime
from pyiceberg.expressions import EqualTo, In

In [ ]:
!mkdir -p warehouse

# Initialize Warehouse and S3 connection

In [ ]:
import boto3
s3_client = boto3.client(
    's3',
    endpoint_url="https://15c46705015d147b9bbf2d532ce26495.r2.cloudflarestorage.com" ,
    aws_access_key_id=userdata.get('PYICEBERG_CATALOG__DEFAULT__S3__ACCESS_KEY_ID'),
    aws_secret_access_key=userdata.get('PYICEBERG_CATALOG__DEFAULT__S3__SECRET_ACCESS_KEY'),
)

In [ ]:
warehouse_path = "/content/warehouse"
s3_uri = "https://15c46705015d147b9bbf2d532ce26495.r2.cloudflarestorage.com"

warehouse_path = "/content/warehouse"
s3_uri = "https://15c46705015d147b9bbf2d532ce26495.r2.cloudflarestorage.com"
catalog = rest.RestCatalog(
    name="default",
    warehouse="15c46705015d147b9bbf2d532ce26495_standard-deviants-storage",
    uri="https://catalog.cloudflarestorage.com/15c46705015d147b9bbf2d532ce26495/standard-deviants-storage",
    token=userdata.get('CLOUDFLARE_API_KEY'),
)

if not catalog.namespace_exists("default"):
  catalog.create_namespace("default")



# Create table using PyArrow schema
q_a_schema = pa.schema([
      ("created_at", pa.timestamp('s'),),
      ("updated_at", pa.timestamp('s'),),
      ("id",pa.int64(),),
      ("minister_id", pa.int64(),),
      ("code", pa.string(),),
      ("question_number", pa.int64(),),
      ("house_id", pa.int64(),),
      ("written_number", pa.int64(),),
      ("oral_number", pa.int64(),),
      ("president_number", pa.int64(),),
      ("deputy_president_number", pa.int64(),),
      ("answer_type", pa.string(),),
      ("date", pa.string(),),
      ("year", pa.int64(),),
      ("question", pa.string(),),
      ("answer", pa.string(),),
      ("question_to_name", pa.string(),),
      ("translated", pa.bool_(),),
      ("asked_by_name", pa.string(),),
      ("asked_by_member_id", pa.int64(),),
      ("source_file_id", pa.int64(),),
      ("url", pa.string(),),
      ("source_file.id", pa.int64(),),
      ("source_file.title", pa.string(),),
      ("source_file.file_mime", pa.string(),),
      ("source_file.file_path", pa.string(),),
      ("source_file.file_bytes", pa.int64(),),
      ("source_file.origname", pa.string(),),
      ("source_file.description", pa.string(),),
      ("source_file.playtime", pa.string(),),
      ("source_file.url", pa.string()),
      ("retrieved_at", pa.timestamp('s'),)
    ])
if not catalog.table_exists("default.questions_and_answers"):
  q_a_table = catalog.create_table("default.questions_and_answers", schema=q_a_schema)
else:
  q_a_table = catalog.load_table("default.questions_and_answers")

def retrieve_question_by_id(idents: list[str]):
  rows = q_a_table.scan(row_filter=In("id", idents)).to_pandas()
  return rows

# Questions and Answers

In [ ]:
import requests
from datetime import UTC
url = "https://api.pmg.org.za/committee-question/"
while True:
  print(url)
  if url is None:
    break
  resp = requests.get(url)
  respj = resp.json()
  retrieved_at = datetime.utcnow()
  results = respj["results"]
  page_data = []
  for jdata in results:
    if "source_file" in jdata:
      sf = jdata["source_file"]
    else:
      sf = {}
      jdata["source_file"] = {}
    jdata = {**jdata, **{f"source_file.{k}": v for k,v in sf.items()}, "retrieved_at" : retrieved_at}
    jdata["created_at"] = datetime.fromisoformat(jdata["created_at"])
    jdata["updated_at"] = datetime.fromisoformat(jdata["updated_at"])
    del jdata["source_file"]
    if "minister" in jdata:
      del jdata["minister"]
    del jdata["house"]
    page_data.append(jdata)
  check_db = retrieve_question_by_id([r["id"] for r in page_data])
  check_db_rows = {r['id']: r['updated_at'] for (_, r) in check_db.iterrows()}
  docs_to_delete = []
  docs_to_append = []
  for row in page_data:
    if row['id'] in check_db_rows and check_db_rows[row['id']].replace(tzinfo=UTC) < row['updated_at'].replace(microsecond=0):
      # delete stale record and reinsert
      docs_to_delete.append(row['id'])
      docs_to_append.append(row)
      print(f"Id {row["id"]} {row["date"]} has newer content ours {check_db_rows[row['id']]} < theirs {row['updated_at']}")
    elif row['id'] in check_db_rows:
      print(f"Id {row["id"]} Already seen ")
      pass
    else:
      docs_to_append.append(row)
      print(f"Id {row['id']} {row["date"]} unseen")
  url = respj["next"]
  if len(docs_to_delete) == 0 and len(docs_to_append) == 0:
    continue
  elif len(docs_to_append) == 0:
    continue
  elif len(docs_to_delete) > 0:
    q_a_table.delete(In("id", docs_to_delete))
  app_tab = pa.Table.from_pylist(docs_to_append, schema=q_a_schema)
  # app_tab.validate(full=True)
  q_a_table.append(app_tab)

In [ ]:
## Show loaded data

In [ ]:
rows = q_a_table.scan().to_pandas()
rows

,created_at,updated_at,id,minister_id,code,question_number,house_id,written_number,oral_number,president_number,...,source_file.id,source_file.title,source_file.file_mime,source_file.file_path,source_file.file_bytes,source_file.origname,source_file.description,source_file.playtime,source_file.url,retrieved_at
0,2025-01-17 11:44:29,2025-01-17 11:46:05,27814,4.0,NW1226,1226,3,1226.0,NaN,NaN,...,183055.0,None,application/vnd.openxmlformats-officedocument....,RNW1226-241224.docx,125205.0,None,None,None,https://pmg.org.za/files/RNW1226-241224.docx,2026-03-14 20:51:44
1,2025-01-17 11:51:59,2025-01-17 11:52:28,27819,27.0,NW1590,1590,3,1590.0,NaN,NaN,...,183061.0,None,application/vnd.openxmlformats-officedocument....,RNW1590-241224.docx,83005.0,None,None,None,https://pmg.org.za/files/RNW1590-241224.docx,2026-03-14 20:51:44
2,2025-01-17 11:47:13,2025-01-17 11:48:28,27815,4.0,NW1450,1450,3,1450.0,NaN,NaN,...,183056.0,None,application/vnd.openxmlformats-officedocument....,RNW1450-241224.docx,121747.0,None,None,None,https://pmg.org.za/files/RNW1450-241224.docx,2026-03-14 20:51:44
3,2025-01-17 10:56:18,2025-01-17 10:56:33,27803,4.0,NW1674,1674,3,1674.0,NaN,NaN,...,183041.0,None,application/vnd.openxmlformats-officedocument....,RNW1674-241224.docx,116418.0,None,None,None,https://pmg.org.za/files/RNW1674-241224.docx,2026-03-14 20:51:44
4,2025-01-17 11:49:55,2025-01-17 11:50:22,27817,4.0,NW1485,1485,3,1485.0,NaN,NaN,...,183059.0,None,application/vnd.openxmlformats-officedocument....,RNW1485-241224.docx,125859.0,None,None,None,https://pmg.org.za/files/RNW1485-241224.docx,2026-03-14 20:51:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8295,2026-03-11 10:13:37,2026-03-11 10:40:59,36047,30.0,NW309,309,3,309.0,NaN,NaN,...,201518.0,None,application/vnd.openxmlformats-officedocument....,RNW309-2026-03-10.docx,17060.0,None,None,None,https://pmg.org.za/files/RNW309-2026-03-10.docx,2026-03-14 19:48:51
8296,2026-03-12 13:47:37,2026-03-12 13:48:30,36088,30.0,NW312,312,3,312.0,NaN,NaN,...,201616.0,None,application/vnd.openxmlformats-officedocument....,RNW312-260310.docx,106960.0,None,None,None,https://pmg.org.za/files/RNW312-260310.docx,2026-03-14 19:48:51
8297,2026-03-12 12:43:53,2026-03-12 12:44:25,36073,30.0,NW725,725,3,725.0,NaN,NaN,...,201600.0,None,application/vnd.openxmlformats-officedocument....,RNW725-260310.docx,2530560.0,None,None,None,https://pmg.org.za/files/RNW725-260310.docx,2026-03-14 19:48:51
8298,2026-03-12 13:17:33,2026-03-12 13:18:14,36076,20.0,NW330,330,3,330.0,NaN,NaN,...,201604.0,None,application/vnd.openxmlformats-officedocument....,RNW330-260310.docx,22934.0,None,None,None,https://pmg.org.za/files/RNW330-260310.docx,2026-03-14 19:48:51
8299,2026-03-12 13:41:03,2026-03-12 13:42:43,36082,1.0,NW78,78,3,78.0,NaN,NaN,...,201610.0,None,application/vnd.openxmlformats-officedocument....,RNW78-260310.docx,29431.0,None,None,None,https://pmg.org.za/files/RNW78-260310.docx,2026-03-14 19:48:51

# Proceedings
## Imports

In [ ]:
!pip install playwright
!playwright install

Collecting playwright
  Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl.metadata (3.5 kB)
Collecting pyee<14,>=13 (from playwright)
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from playwright) (3.3.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from pyee<14,>=13->playwright) (4.15.0)
Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl (46.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 56.7 MB/s eta 0:00:00
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Installing collected packages: pyee, playwright
Successfully installed playwright-1.58.0 pyee-13.0.1
Downloading Chrome for Testing 145.0.7632.6 (playwright chromium v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-linux64.zip
(node:3815) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
167.3 MiB [] 0% 0.0s167.3 MiB [] 0% 118.0s167.3 MiB [] 0% 378.7s167.3 MiB [] 0% 432.8s167.3 MiB [] 0% 347.2s167.3 MiB [] 0% 299.7s167.3 MiB [] 0% 269.5s167.3 MiB [] 0% 249.4s167.3 MiB [] 0% 233.2s167.3 MiB [] 0% 218.9s167.3 MiB [] 0% 205.4s167.3 MiB [] 0% 193.9s167.3 MiB [] 0% 170.5s167.3 MiB [] 0% 153.6s167.3 MiB [] 0% 140.4s167.3 MiB [] 0% 130.4s167.3 MiB [] 0% 122.3s167.3 MiB [] 0% 112.7s167.3 MiB [] 0% 102.9s167.3 MiB [] 0% 93.5s167.3 MiB [] 0% 89.2s167.3 MiB [] 0% 86.1s167.3 MiB [] 0% 78.4s167.3 MiB [] 0% 70.5s167.3 MiB [] 0% 65.7s167.3 MiB [] 0% 63.7s167.3 MiB [] 1% 62.9s167.3 MiB [] 1% 59.4s167.3 MiB [] 1% 53.4s167.3 MiB [] 1% 47.8s167.3 MiB [] 1% 47.1s167.3 MiB [] 1% 47.0s167.3 MiB [] 1% 45.7s167.3 MiB [] 1% 41.7s167.3 MiB [] 2% 37.5s167.3 MiB [] 2% 34.9s167.3 MiB [] 2% 35.1s167.3 MiB [] 2% 35.2s167.3 MiB [] 2% 31.8s167.3 MiB [] 2% 29.1s167.3 MiB [] 3% 26.2s167.3 MiB [] 3% 26.3s167.3 MiB [] 3% 26.5s167.3 MiB [] 3% 24.4s167.3 MiB [] 4% 22.1s167.3 MiB [] 4% 20.1s167.3 MiB [] 4% 19.6s167.3 MiB [] 4% 19.8s167.3 MiB [] 5% 18.9s167.3 MiB [] 5% 17.1s167.3 MiB [] 6% 15.5s167.3 MiB [] 6% 14.5s167.3 MiB [] 6% 14.7s167.3 MiB [] 7% 14.0s167.3 MiB [] 7% 13.0s167.3 MiB [] 8% 12.1s167.3 MiB [] 8% 11.8s167.3 MiB [] 9% 11.2s167.3 MiB [] 10% 10.4s167.3 MiB [] 10% 9.9s167.3 MiB [] 11% 10.0s167.3 MiB [] 11% 9.4s167.3 MiB [] 12% 8.9s167.3 MiB [] 13% 8.7s167.3 MiB [] 14% 8.3s167.3 MiB [] 14% 7.9s167.3 MiB [] 15% 7.8s167.3 MiB [] 16% 7.4s167.3 MiB [] 16% 7.2s167.3 MiB [] 17% 7.0s167.3 MiB [] 18% 6.8s167.3 MiB [] 19% 6.5s167.3 MiB [] 19% 6.4s167.3 MiB [] 20% 6.2s167.3 MiB [] 21% 6.0s167.3 MiB [] 21% 5.9s167.3 MiB [] 22% 6.0s167.3 MiB [] 22% 5.8s167.3 MiB [] 23% 5.6s167.3 MiB [] 24% 5.5s167.3 MiB [] 24% 5.4s167.3 MiB [] 25% 5.2s167.3 MiB [] 26% 5.2s167.3 MiB [] 27% 5.0s167.3 MiB [] 27% 4.9s167.3 MiB [] 28% 4.9s167.3 MiB [] 29% 4.7s167.3 MiB [] 30% 4.6s167.3 MiB [] 31% 4.5s167.3 MiB [] 32% 4.4s167.3 MiB [] 32% 4.3s167.3 MiB [] 33% 4.2s167.3 MiB [] 34% 4.1s167.3 MiB [] 35% 4.1s167.3 MiB [] 35% 4.0s167.3 MiB [] 36% 3.9s167.3 MiB [] 37% 3.9s167.3 MiB [] 38% 3.8s167.3 MiB [] 38% 3.7s167.3 MiB [] 39% 3.6s167.3 MiB [] 40% 3.6s167.3 MiB [] 40% 3.5s167.3 MiB [] 41% 3.5s167.3 MiB [] 42% 3.4s167.3 MiB [] 43% 3.3s167.3 MiB [] 44% 3.2s167.3 MiB [] 45% 3.1s167.3 MiB [] 46% 3.1s167.3 MiB [] 46% 3.0s167.3 MiB [] 47% 3.0s167.3 MiB [] 48% 2.9s167.3 MiB [] 49% 2.8s167.3 MiB [] 50% 2.7s167.3 MiB [] 50% 2.8s167.3 MiB [] 51% 2.7s167.3 MiB [] 51% 2.6s167.3 MiB [] 52% 2.6s167.3 MiB [] 53% 2.6s167.3 MiB [] 54% 2.5s167.3 MiB [] 54% 2.4s167.3 MiB [] 54% 2.5s167.3 MiB [] 55% 2.4s167.3 MiB [] 56% 2.4s167.3 MiB [] 56% 2.3s167.3 MiB [] 57% 2.3s167.3 MiB [] 58% 2.2s167.3 MiB [] 59% 2.2s167.3 MiB [] 59% 2.1s167.3 MiB [] 60% 2.1s167.3 MiB [] 61% 2.0s167.3 MiB [] 61% 2.1s167.3 MiB [] 62% 2.0s167.3 MiB [] 63% 1.9s167.3 MiB [] 64% 1.9s167.3 MiB [] 64% 1.8s167.3 MiB [] 65% 1.8s167.3 MiB [] 66% 1.7s167.3 MiB [] 67% 1.7s167.3 MiB [] 67% 1.6s167.3 MiB [] 67% 1.7s167.3 MiB [] 68% 1.6s167.3 MiB [] 69% 1.6s167.3 MiB [] 70% 1.5s167.3 MiB [] 71% 1.5s167.3 MiB [] 72% 1.4s167.3 MiB [] 73% 1.3s167.3 MiB [] 74% 1.3s167.3 MiB [] 75% 1.3s167.3 MiB [] 75% 1.2s167.3 MiB [] 76% 1.2s167.3 MiB [] 77% 1.1s167.3 MiB [] 78% 1.1s167.3 MiB [] 79% 1.0s167.3 MiB [] 80% 1.0s167.3 MiB [] 81% 0.9s167.3 MiB [] 82% 0.9s167.3 MiB [] 83% 0.8s167.3 MiB [] 84% 0.8s167.3 MiB [] 85% 0.7s167.3 MiB [] 86% 0.7s167.3 MiB [] 86% 0.6s167.3 MiB [] 87% 0.6s167.3 MiB [] 88% 0.6s167.3 MiB [] 88% 0.5s167.3 MiB [] 89% 0.5s167.3 MiB [] 90% 0.5s167.3 MiB [] 91% 0.4s167.3 MiB [] 92% 0.4s167.3 MiB [] 93% 0.3s167.3 MiB [] 94% 0.3s167.3 MiB [] 95% 0.2s167.3 MiB [] 96% 0.2s167.3 MiB [] 96% 0.1s167.3 MiB [] 97% 0.1s167.3 MiB [] 98% 0.1s167.3 MiB [] 99% 0.0s167.3 MiB [] 100% 0.0s
Chrome for Testing 145.0.7632.6 (playwright chromium v1208) downloaded to /root/.cache/ms-playwright/chromium-1208
Downloading Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-headless-shell-linux64.zip
(node:3862) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
110.9 MiB [] 0% 0.0s110.9 MiB [] 0% 78.2s110.9 MiB [] 0% 251.0s110.9 MiB [] 0% 286.8s110.9 MiB [] 0% 230.1s110.9 MiB [] 0% 198.6s110.9 MiB [] 0% 179.2s110.9 MiB [] 0% 166.7s110.9 MiB [] 0% 159.4s110.9 MiB [] 0% 149.6s110.9 MiB [] 0% 140.4s110.9 MiB [] 0% 132.4s110.9 MiB [] 0% 120.0s110.9 MiB [] 0% 106.9s110.9 MiB [] 0% 97.1s110.9 MiB [] 0% 89.6s110.9 MiB [] 0% 84.0s110.9 MiB [] 0% 77.1s110.9 MiB [] 0% 70.3s110.9 MiB [] 0% 63.6s110.9 MiB [] 0% 59.4s110.9 MiB [] 0% 57.5s110.9 MiB [] 1% 52.8s110.9 MiB [] 1% 47.9s110.9 MiB [] 1% 45.0s110.9 MiB [] 1% 43.0s110.9 MiB [] 1% 42.7s110.9 MiB [] 1% 39.5s110.9 MiB [] 1% 35.4s110.9 MiB [] 2% 32.1s110.9 MiB [] 2% 31.4s110.9 MiB [] 2% 31.5s110.9 MiB [] 2% 29.5s110.9 MiB [] 2% 26.6s110.9 MiB [] 3% 24.0s110.9 MiB [] 3% 23.5s110.9 MiB [] 3% 23.7s110.9 MiB [] 3% 22.4s110.9 MiB [] 3% 20.2s110.9 MiB [] 4% 18.4s110.9 MiB [] 4% 17.4s110.9 MiB [] 4% 17.6s110.9 MiB [] 5% 16.7s110.9 MiB [] 5% 15.1s110.9 MiB [] 6% 13.7s110.9 MiB [] 6% 13.0s110.9 MiB [] 6% 13.1s110.9 MiB [] 7% 12.0s110.9 MiB [] 8% 10.8s110.9 MiB [] 9% 9.7s110.9 MiB [] 10% 9.5s110.9 MiB [] 10% 9.6s110.9 MiB [] 10% 8.8s110.9 MiB [] 11% 8.2s110.9 MiB [] 12% 7.5s110.9 MiB [] 13% 7.4s110.9 MiB [] 14% 6.9s110.9 MiB [] 15% 6.5s110.9 MiB [] 16% 6.1s110.9 MiB [] 16% 6.2s110.9 MiB [] 17% 5.8s110.9 MiB [] 18% 5.5s110.9 MiB [] 19% 5.2s110.9 MiB [] 20% 5.3s110.9 MiB [] 21% 5.0s110.9 MiB [] 22% 4.8s110.9 MiB [] 23% 4.7s110.9 MiB [] 24% 4.5s110.9 MiB [] 25% 4.3s110.9 MiB [] 26% 4.2s110.9 MiB [] 27% 4.0s110.9 MiB [] 28% 3.8s110.9 MiB [] 29% 3.7s110.9 MiB [] 31% 3.6s110.9 MiB [] 32% 3.5s110.9 MiB [] 33% 3.4s110.9 MiB [] 34% 3.3s110.9 MiB [] 35% 3.1s110.9 MiB [] 36% 3.1s110.9 MiB [] 37% 3.0s110.9 MiB [] 38% 2.9s110.9 MiB [] 39% 2.8s110.9 MiB [] 40% 2.7s110.9 MiB [] 42% 2.6s110.9 MiB [] 43% 2.6s110.9 MiB [] 44% 2.5s110.9 MiB [] 45% 2.4s110.9 MiB [] 46% 2.3s110.9 MiB [] 47% 2.3s110.9 MiB [] 48% 2.2s110.9 MiB [] 49% 2.1s110.9 MiB [] 50% 2.1s110.9 MiB [] 51% 2.0s110.9 MiB [] 53% 2.0s110.9 MiB [] 54% 1.9s110.9 MiB [] 55% 1.8s110.9 MiB [] 56% 1.8s110.9 MiB [] 57% 1.7s110.9 MiB [] 58% 1.7s110.9 MiB [] 59% 1.6s110.9 MiB [] 60% 1.6s110.9 MiB [] 61% 1.5s110.9 MiB [] 62% 1.4s110.9 MiB [] 62% 1.5s110.9 MiB [] 63% 1.4s110.9 MiB [] 65% 1.3s110.9 MiB [] 66% 1.3s110.9 MiB [] 67% 1.3s110.9 MiB [] 68% 1.2s110.9 MiB [] 69% 1.2s110.9 MiB [] 70% 1.1s110.9 MiB [] 71% 1.1s110.9 MiB [] 72% 1.0s110.9 MiB [] 73% 1.0s110.9 MiB [] 74% 0.9s110.9 MiB [] 75% 0.9s110.9 MiB [] 76% 0.9s110.9 MiB [] 77% 0.8s110.9 MiB [] 78% 0.8s110.9 MiB [] 79% 0.8s110.9 MiB [] 80% 0.7s110.9 MiB [] 81% 0.7s110.9 MiB [] 82% 0.6s110.9 MiB [] 83% 0.6s110.9 MiB [] 84% 0.5s110.9 MiB [] 85% 0.5s110.9 MiB [] 87% 0.5s110.9 MiB [] 88% 0.4s110.9 MiB [] 89% 0.4s110.9 MiB [] 90% 0.3s110.9 MiB [] 91% 0.3s110.9 MiB [] 92% 0.3s110.9 MiB [] 93% 0.2s110.9 MiB [] 94% 0.2s110.9 MiB [] 95% 0.1s110.9 MiB [] 96% 0.1s110.9 MiB [] 97% 0.1s110.9 MiB [] 99% 0.0s110.9 MiB [] 100% 0.0s
Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) downloaded to /root/.cache/ms-playwright/chromium_headless_shell-1208
Downloading Firefox 146.0.1 (playwright firefox v1509) from https://cdn.playwright.dev/dbazure/download/playwright/builds/firefox/1509/firefox-ubuntu-22.04.zip
(node:3897) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
99.5 MiB [] 0% 0.0s99.5 MiB [] 0% 3.1s99.5 MiB [] 2% 1.1s99.5 MiB [] 5% 0.8s99.5 MiB [] 8% 0.7s99.5 MiB [] 12% 0.5s99.5 MiB [] 16% 0.5s99.5 MiB [] 19% 0.5s99.5 MiB [] 22% 0.4s99.5 MiB [] 26% 0.4s99.5 MiB [] 31% 0.4s99.5 MiB [] 35% 0.3s99.5 MiB [] 39% 0.3s99.5 MiB [] 43% 0.3s99.5 MiB [] 48% 0.2s99.5 MiB [] 48% 0.4s99.5 MiB [] 52% 0.3s99.5 MiB [] 57% 0.3s99.5 MiB [] 62% 0.2s99.5 MiB [] 64% 0.3s99.5 MiB [] 69% 0.2s99.5 MiB [] 73% 0.2s99.5 MiB [] 78% 0.1s99.5 MiB [] 82% 0.1s99.5 MiB [] 86% 0.1s99.5 MiB [] 91% 0.1s99.5 MiB [] 97% 0.0s99.5 MiB [] 100% 0.0s
Firefox 146.0.1 (playwright firefox v1509) downloaded to /root/.cache/ms-playwright/firefox-1509
Downloading WebKit 26.0 (playwright webkit v2248) from https://cdn.playwright.dev/dbazure/download/playwright/builds/webkit/2248/webkit-ubuntu-22.04.zip
(node:3920) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
99.4 MiB [] 0% 0.0s99.4 MiB [] 0% 2.4s99.4 MiB [] 2% 1.3s99.4 MiB [] 5% 0.9s99.4 MiB [] 8% 0.8s99.4 MiB [] 12% 0.6s99.4 MiB [] 14% 2.0s99.4 MiB [] 17% 1.6s99.4 MiB [] 19% 1.5s99.4 MiB [] 22% 1.3s99.4 MiB [] 23% 1.2s99.4 MiB [] 26% 1.2s99.4 MiB [] 29% 2.0s99.4 MiB [] 31% 1.9s99.4 MiB [] 34% 1.7s99.4 MiB [] 37% 1.5s99.4 MiB [] 42% 1.3s99.4 MiB [] 44% 1.2s99.4 MiB [] 47% 1.1s99.4 MiB [] 49% 1.0s99.4 MiB [] 52% 0.9s99.4 MiB [] 56% 0.8s99.4 MiB [] 60% 0.7s99.4 MiB [] 63% 0.6s99.4 MiB [] 67% 0.6s99.4 MiB [] 72% 0.4s99.4 MiB [] 75% 0.4s99.4 MiB [] 80% 0.3s99.4 MiB [] 83% 0.2s99.4 MiB [] 86% 0.2s99.4 MiB [] 89% 0.1s99.4 MiB [] 94% 0.1s99.4 MiB [] 98% 0.0s99.4 MiB [] 100% 0.0s
WebKit 26.0 (playwright webkit v2248) downloaded to /root/.cache/ms-playwright/webkit-2248
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
(node:3946) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
2.3 MiB [] 0% 0.0s2.3 MiB [] 25% 0.0s2.3 MiB [] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /root/.cache/ms-playwright/ffmpeg-1011
Playwright Host validation warning:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     playwright install-deps                          ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     apt-get install libxcomposite1\                  ║
║         libgtk-3-0\                                  ║
║         libatk1.0-0                                  ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/dependencies.js:269:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async Registry._validateHostRequirements (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/index.js:991:14)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/index.js:1113:7)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/index.js:1102:7)
    at async i.<anonymous> (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/cli/program.js:174:7)

In [ ]:
import asyncio
import requests
import fitz
import pytesseract
from PIL import Image
import io
from playwright.async_api import async_playwright
import pandas as pd

## Initialize Warehouse Connection

In [ ]:
warehouse_path = "/content/warehouse"
s3_uri = "https://15c46705015d147b9bbf2d532ce26495.r2.cloudflarestorage.com"
catalog = rest.RestCatalog(
    name="default",
    warehouse="15c46705015d147b9bbf2d532ce26495_standard-deviants-storage",
    uri="https://catalog.cloudflarestorage.com/15c46705015d147b9bbf2d532ce26495/standard-deviants-storage",
    token=userdata.get('CLOUDFLARE_API_KEY'),
)
if not catalog.namespace_exists("default"):
  catalog.create_namespace("default")

table_name = "default.proceedings"

# Drop table if it exists
if catalog.table_exists(table_name):
    catalog.drop_table(table_name)
    print(f"{table_name} dropped.")


# Create table using PyArrow schema
proceedings_schema = pa.schema([
    ("id", pa.int64()),
    ("uvimba_id", pa.string()),
    ("document_name", pa.string()),
    ("house", pa.string()),
    ("language", pa.string()),
    ("date", pa.string()),
    ("document_type", pa.string()),
    ("file_location", pa.string()),
    ("pdf_url", pa.string()),
    ("pdf_text", pa.string()),
])

if not catalog.table_exists(table_name):
  proceedings_table = catalog.create_table(table_name, schema=proceedings_schema)
else:
  proceedings_table = catalog.load_table(table_name)

default.proceedings dropped.

In [ ]:
import fitz  # PyMuPDF
import pytesseract
from pdf2image import convert_from_bytes

In [ ]:
def extract_pdf_text(url, stop_page=70):
    # Fetch PDF from URL
    import requests
    pdf_bytes = requests.get(url).content

    # Open PDF with fitz
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    text_output = ""

    for i, page in enumerate(doc):
        if i + 1 > stop_page:  # Stop at the specified page
            break

        page_text = page.get_text()

        # If the text contains garbage like '(cid:', apply OCR
        if page_text and '(cid:' in page_text:
            print(f"Page {i + 1} is an annexure, applying OCR...")

            # Convert the PDF page to image
            images = convert_from_bytes(pdf_bytes, first_page=i+1, last_page=i+1, dpi=300)
            for img in images:
                ocr_text = pytesseract.image_to_string(img)
                text_output += ocr_text + "\n\n"
        else:
            text_output += page_text + "\n\n"

    return text_output

In [ ]:
import requests
import re
from io import BytesIO

def sanitize_proceedings_filename(name: str) -> str:
    name = re.sub(r'[\\/*?:"<>|]', "", name)
    name = name.replace(" ", "_")
    return name

from io import BytesIO
import requests

def upload_documents_to_s3(documents, s3_client, bucket_name):

    uploaded = 0

    for doc in documents:
        try:

            pdf_url = doc["pdf_url"]
            doc_id = doc["id"]

            filename = f"{doc_id}.pdf"
            s3_key = f"proceedings/{filename}"

            print(f"Uploading {filename}...")

            response = requests.get(pdf_url)

            if response.status_code != 200:
                print(f"Failed to download {pdf_url}")
                continue

            file_bytes = BytesIO(response.content)

            s3_client.upload_fileobj(
                file_bytes,
                bucket_name,
                s3_key
            )

            uploaded += 1

        except Exception as e:
            print(f"Upload failed for {doc['document_name']}: {e}")

    print(f"{uploaded} files uploaded to s3://{bucket_name}/proceedings/")

## Hansard

In [ ]:
import requests
import pandas as pd
import pyarrow as pa

url = "https://www.parliament.gov.za/docsjson/hansard"

params = {
    "queries[type]": "hansard",
    "sorts[date]": "-1",
    "page": 1,
    "perPage": 380,
    "offset": 0
}

print("Fetching Hansard records from API...")

response = requests.get(url, params=params)
data = response.json()

records = data["records"]

documents = []

for record in records:

    name = record["name"]
    house = record["house"]
    language = record["language"]
    date = record["date"]
    doc_type = record["type"]
    file_location = record["file_location"]

    pdf_url = f"https://www.parliament.gov.za/storage/app/media/Docs/{file_location}"

    print("Name:", name)
    print("House:", house)
    print("Language:", language)
    print("Date:", date)
    print("Type:", doc_type)
    print("File location:", file_location)
    print("PDF URL:", pdf_url)

    text = extract_pdf_text(pdf_url)

    documents.append({
        "id": record["id"],
        "uvimba_id": record["uVIMBA_id"],
        "document_name": name,
        "house": house,
        "language": language,
        "date": date,
        "document_type": doc_type,
        "file_location": file_location,
        "pdf_url": pdf_url,
        "pdf_text": text
    })


if documents:

    df = pd.DataFrame(documents)

    arrow_table = pa.Table.from_pandas(df)

    print("appending to proceedings table")

    proceedings_table.append(arrow_table)

    print(f"{len(df)} Hansard documents inserted into Iceberg table.")

    s3_client.upload_file(local_file_path, bucket_name, s3_object_key)

    print(f"Catalog uploaded to s3://{bucket_name}/{s3_object_key}")

    upload_documents_to_s3(documents, s3_client, bucket_name)

    rows = proceedings_table.scan().to_pandas()

    print("\nData currently in Hansard Iceberg table:\n")
    print(rows)

Fetching Hansard records from API...
Name: HAN-MPS-NA(2)-2026-03-06-UH.pdf
House: NA
Language: ENG
Date: 2026-03-06
Type: HANSARD
File location: hansard/01mfgh4vw5ff6kwu57l5glxmuwmneo6zsg.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vw5ff6kwu57l5glxmuwmneo6zsg.pdf
Name: HAN-NCOP-2026-03-05-UH.pdf
House: NCOP
Language: ENG
Date: 2026-03-05
Type: HANSARD
File location: hansard/01mfgh4vw6p77fogtl4rbywcnoxrphclb3.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vw6p77fogtl4rbywcnoxrphclb3.pdf
Name: HAN-NA-2026-03-05-UH.pdf
House: NA
Language: ENG
Date: 2026-03-05
Type: HANSARD
File location: hansard/01mfgh4vv7nz6y7l524rc3vinrur2dh42f.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vv7nz6y7l524rc3vinrur2dh42f.pdf
Name: HAN-NA-2026-03-04-UH.pdf
House: NA
Language: ENG
Date: 2026-03-04
Type: HANSARD
File location: hansard/01mfgh4vufc3w4csruijhiftfar4hdyo5o.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vufc3w4csruijhiftfar4hdyo5o.pdf
Name: HAN-NCOP-2026-03-04-UH.pdf
House: NCOP
Language: ENG
Date: 2026-03-04
Type: HANSARD
File location: hansard/01mfgh4vqxparfe7256nbk35f3vpu35bcl.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vqxparfe7256nbk35f3vpu35bcl.pdf
Name: HAN-NA-2026-03-03-UH.pdf
House: NA
Language: ENG
Date: 2026-03-03
Type: HANSARD
File location: hansard/01mfgh4vun4lp2itg2wrhi2u2mmlrrok2u.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vun4lp2itg2wrhi2u2mmlrrok2u.pdf
Name: HAN-NCOP-2026-02-27-UH.pdf
House: NCOP
Language: ENG
Date: 2026-02-27
Type: HANSARD
File location: hansard/01mfgh4vuhqrmlggwxvrhl355loh64pw4n.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vuhqrmlggwxvrhl355loh64pw4n.pdf
Name: HAN-NA-2026-02-25-UH.pdf
House: NA
Language: ENG
Date: 2026-02-25
Type: HANSARD
File location: hansard/01mfgh4vrodmzv6v5f2jhzl52y6jpr2upy.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vrodmzv6v5f2jhzl52y6jpr2upy.pdf
Name: HAN-NA-2026-02-24-UH.pdf
House: NA
Language: ENG
Date: 2026-02-24
Type: HANSARD
File location: hansard/01mfgh4vwb3l4w56dzrjeizk2pdcvuddga.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vwb3l4w56dzrjeizk2pdcvuddga.pdf
Name: HAN-JNT-2026-02-19-UH.pdf
House: JOINT
Language: ENG
Date: 2026-02-19
Type: HANSARD
File location: hansard/01mfgh4vxjcsgoamgklvdjvaac5nobarqd.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vxjcsgoamgklvdjvaac5nobarqd.pdf
Name: HAN-JNT-2026-02-19.pdf
House: JOINT
Language: ENG
Date: 2026-02-19
Type: HANSARD
File location: hansard/01mfgh4vxyymvkxiqkoraz3nxexprkgvzr.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vxyymvkxiqkoraz3nxexprkgvzr.pdf
Name: HAN-JS-2026-02-18-UH.pdf
House: JOINT
Language: ENG
Date: 2026-02-18
Type: HANSARD
File location: hansard/01mfgh4vxrmmzhhou5mbb3dxxg5paylhus.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vxrmmzhhou5mbb3dxxg5paylhus.pdf
Name: HAN-NA-2026-02-17.pdf
House: NA
Language: ENG
Date: 2026-02-17
Type: HANSARD
File location: hansard/01mfgh4vr53extcknkrfairmed5esd3feh.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vr53extcknkrfairmed5esd3feh.pdf
Name: HAN-JNT-2026-02-17-UH.pdf
House: JOINT
Language: ENG
Date: 2026-02-17
Type: HANSARD
File location: hansard/01mfgh4vxmd3k4fslbabcj6ho2je3mhpju.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vxmd3k4fslbabcj6ho2je3mhpju.pdf
Name: HAN-JNT-2026-02-12.pdf
House: JOINT
Language: ENG
Date: 2026-02-12
Type: HANSARD
File location: hansard/01mfgh4vqdhaf4dyjb5jg24xyrqw2zr5up.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vqdhaf4dyjb5jg24xyrqw2zr5up.pdf
Name: HAN-NCOP-2026-02-06-UH.pdf
House: NCOP
Language: ENG
Date: 2026-02-06
Type: HANSARD
File location: hansard/01mfgh4vu5vct7wilorzh3jea6nm4oprpv.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vu5vct7wilorzh3jea6nm4oprpv.pdf
Name: HAN-NCOP-2026-02-06.pdf
House: NCOP
Language: ENG
Date: 2026-02-06
Type: HANSARD
File location: hansard/01mfgh4vuttsfvc5gdpfhjgfi5sxnw4mft.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vuttsfvc5gdpfhjgfi5sxnw4mft.pdf
Name: HAN-NCOP-2026-01-15-UH.pdf
House: NCOP
Language: ENG
Date: 2026-01-15
Type: HANSARD
File location: hansard/01mfgh4vqsfgnflphsojelneljbloxc77g.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vqsfgnflphsojelneljbloxc77g.pdf
Name: HAN-NA-2026-01-13-UH.pdf
House: NA
Language: ENG
Date: 2026-01-13
Type: HANSARD
File location: hansard/01mfgh4vs4z7xg34cehbck36iloo4dofcj.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vs4z7xg34cehbck36iloo4dofcj.pdf
Name: HAN-NCOP-2025-12-17-UH.pdf
House: NCOP
Language: ENG
Date: 2025-12-17
Type: HANSARD
File location: hansard/01mfgh4vszoozmko67cvhktcfdbjyd6nf4.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vszoozmko67cvhktcfdbjyd6nf4.pdf
Name: HAN-NCOP-2025-12-04-UH.pdf
House: NCOP
Language: ENG
Date: 2025-12-04
Type: HANSARD
File location: hansard/01mfgh4vsm4k227gzgyng2qgvpkj6katvd.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vsm4k227gzgyng2qgvpkj6katvd.pdf
Name: HAN-NA-2025-12-04-UH.pdf
House: NA
Language: ENG
Date: 2025-12-04
Type: HANSARD
File location: hansard/01mfgh4vrxjpq364jwk5bjnlxcgrvmkvwu.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vrxjpq364jwk5bjnlxcgrvmkvwu.pdf
Name: HAN-NA-2025-12-03-UH.pdf
House: NA
Language: ENG
Date: 2025-12-03
Type: HANSARD
File location: hansard/01mfgh4vwztobs5lkglfb24ilbpetks6yr.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vwztobs5lkglfb24ilbpetks6yr.pdf
Name: HAN-NCOP-2025-12-02-UH.pdf
House: NCOP
Language: ENG
Date: 2025-12-02
Type: HANSARD
File location: hansard/01mfgh4vt76ee5nxdwgrfysm3q5bxr6i4o.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vt76ee5nxdwgrfysm3q5bxr6i4o.pdf
Name: HAN-NA-2025-12-02-UH.pdf
House: NA
Language: ENG
Date: 2025-12-02
Type: HANSARD
File location: hansard/01mfgh4vs4zuz4vyop7jby65euuo5twvny.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vs4zuz4vyop7jby65euuo5twvny.pdf
Name: HAN-MPS-NA(1)-2025-11-28-UH.pdf
House: NA
Language: ENG
Date: 2025-11-28
Type: HANSARD
File location: hansard/01mfgh4vq7dppejpo3yzckjypzabqy3642.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vq7dppejpo3yzckjypzabqy3642.pdf
Name: HAN-MPS-NA(2)-2025-11-28-UH.pdf
House: NA
Language: ENG
Date: 2025-11-28
Type: HANSARD
File location: hansard/01mfgh4vvu3ittxcbtofajecoip2r5e5ie.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vvu3ittxcbtofajecoip2r5e5ie.pdf
Name: HAN-NCOP-2025-11-27-UH.pdf
House: NCOP
Language: ENG
Date: 2025-11-27
Type: HANSARD
File location: hansard/01mfgh4vrpzl7wwhrbazalpkrzxklsbry2.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vrpzl7wwhrbazalpkrzxklsbry2.pdf
Name: HAN-NA-2025-11-27-UH.pdf
House: NA
Language: ENG
Date: 2025-11-27
Type: HANSARD
File location: hansard/01mfgh4vqblcps55tx5rflxknwojdz3kla.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vqblcps55tx5rflxknwojdz3kla.pdf
Name: HAN-NA-2025-11-26-UH.pdf
House: NA
Language: ENG
Date: 2025-11-26
Type: HANSARD
File location: hansard/01mfgh4vwurgkeigisi5b2frew3iyos7ta.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vwurgkeigisi5b2frew3iyos7ta.pdf
Name: HAN-NCOP-2025-11-25-UH.pdf
House: NCOP
Language: ENG
Date: 2025-11-25
Type: HANSARD
File location: hansard/01mfgh4vs4jjj4uf3ksvgjjg4hwfsdhilj.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vs4jjj4uf3ksvgjjg4hwfsdhilj.pdf
Name: HAN-NA-2025-11-25-UH.pdf
House: NA
Language: ENG
Date: 2025-11-25
Type: HANSARD
File location: hansard/01mfgh4vv3srvtj5ylxjgj4phkxe4jz6az.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vv3srvtj5ylxjgj4phkxe4jz6az.pdf
Name: HAN-NCOP-2025-11-13-UH.pdf
House: NCOP
Language: ENG
Date: 2025-11-13
Type: HANSARD
File location: hansard/01mfgh4vuzgfvugn4l2jbyfkxt5pb3anw5.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vuzgfvugn4l2jbyfkxt5pb3anw5.pdf
Name: HAN-MPS-NA(2)-2025-11-13-UH.pdf
House: NA
Language: ENG
Date: 2025-11-13
Type: HANSARD
File location: hansard/01mfgh4vwgg277pjqokfh3hnb7ejfond7q.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vwgg277pjqokfh3hnb7ejfond7q.pdf
Name: HAN-MPS-NA(1)-2025-11-13-UH.pdf
House: NA
Language: ENG
Date: 2025-11-13
Type: HANSARD
File location: hansard/01mfgh4vtx4ko24cdzlnhkfrwjs6gncc3n.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vtx4ko24cdzlnhkfrwjs6gncc3n.pdf
Name: HAN-NA-2025-11-12-UH.pdf
House: NA
Language: ENG
Date: 2025-11-12
Type: HANSARD
File location: hansard/01mfgh4vwpdh7m3hhqgfay5bma4wofdt4a.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vwpdh7m3hhqgfay5bma4wofdt4a.pdf
Name: HAN-NA-2025-11-11-UH.pdf
House: NA
Language: ENG
Date: 2025-11-11
Type: HANSARD
File location: hansard/01mfgh4vxhaxpbxuqoc5hyeg5r4sxlzipt.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vxhaxpbxuqoc5hyeg5r4sxlzipt.pdf
Name: HAN-MPS-NA(2)-2025-11-07-UH.pdf
House: NA
Language: ENG
Date: 2025-11-07
Type: HANSARD
File location: hansard/01mfgh4vxlbcaj4qyslvelyv2vijecb6qg.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vxlbcaj4qyslvelyv2vijecb6qg.pdf
Name: HAN-MPS-NA(3)-2025-11-07-UH.pdf
House: NA
Language: ENG
Date: 2025-11-07
Type: HANSARD
File location: hansard/01mfgh4vrs3qgwmuikj5cj6rievwhcqf6k.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vrs3qgwmuikj5cj6rievwhcqf6k.pdf
Name: HAN-MPS-NA(1)-2025-11-07-UH.pdf
House: NA
Language: ENG
Date: 2025-11-07
Type: HANSARD
File location: hansard/01mfgh4vutyzts4uaba5cztsdlwmnc2ggh.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vutyzts4uaba5cztsdlwmnc2ggh.pdf
Name: HAN-NA-2025-11-06-UH.pdf
House: NA
Language: ENG
Date: 2025-11-06
Type: HANSARD
File location: hansard/01mfgh4vtueluanrwtlvcz26tirhs7plxl.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vtueluanrwtlvcz26tirhs7plxl.pdf
Name: HAN-NA-2025-11-05-UH.pdf
House: NA
Language: ENG
Date: 2025-11-05
Type: HANSARD
File location: hansard/01mfgh4vqcko5uoybssrg2ruufmfsfbc5g.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vqcko5uoybssrg2ruufmfsfbc5g.pdf
Name: HAN-NCOP-2025-11-04-UH.pdf
House: NCOP
Language: ENG
Date: 2025-11-04
Type: HANSARD
File location: hansard/01mfgh4vqnkt3zj6xgwbezd7xkkmtevhbs.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vqnkt3zj6xgwbezd7xkkmtevhbs.pdf
Name: HAN-NA-2025-11-04-UH.pdf
House: NA
Language: ENG
Date: 2025-11-04
Type: HANSARD
File location: hansard/01mfgh4vuas677agsiprcljnoymx7uoc3r.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vuas677agsiprcljnoymx7uoc3r.pdf
Name: HAN-MPS-NA(1)-2025-10-31-UH.pdf
House: NA
Language: ENG
Date: 2025-10-31
Type: HANSARD
File location: hansard/01mfgh4vtwcyucgmkhifczz3pwzhe5l3fq.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vtwcyucgmkhifczz3pwzhe5l3fq.pdf
Name: HAN-MPS-NA(2)-2025-10-31-UH.pdf
House: NA
Language: ENG
Date: 2025-10-31
Type: HANSARD
File location: hansard/01mfgh4vqxjllccz7pavdjevsaiydtkbnn.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vqxjllccz7pavdjevsaiydtkbnn.pdf
Name: HAN-NA-2025-10-30-UH.pdf
House: NA
Language: ENG
Date: 2025-10-30
Type: HANSARD
File location: hansard/01mfgh4vrlowlidbd2hnbih22my4p3w3dy.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vrlowlidbd2hnbih22my4p3w3dy.pdf
Name: HAN-NCOP-2025-10-30-UH.pdf
House: NCOP
Language: ENG
Date: 2025-10-30
Type: HANSARD
File location: hansard/01mfgh4vwiswxyisrjhrgkkhi6inaokq64.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vwiswxyisrjhrgkkhi6inaokq64.pdf
Name: HAN-NCOP-2025-10-29-UH.pdf
House: NCOP
Language: ENG
Date: 2025-10-29
Type: HANSARD
File location: hansard/01mfgh4vq2z2ekiie2vne37zhxgcgnlcbi.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vq2z2ekiie2vne37zhxgcgnlcbi.pdf
Name: HAN-NA-2025-10-29-UH.pdf
House: NA
Language: ENG
Date: 2025-10-29
Type: HANSARD
File location: hansard/01mfgh4vqvsnj2zs3jjfb3sjm4ogzekou2.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vqvsnj2zs3jjfb3sjm4ogzekou2.pdf
Name: HAN-NA-2025-10-28-UH.pdf
House: NA
Language: ENG
Date: 2025-10-28
Type: HANSARD
File location: hansard/01mfgh4vsmhy7zykkvj5dzhagtexysm3ej.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vsmhy7zykkvj5dzhagtexysm3ej.pdf
Name: HAN-NCOP-2025-10-23-UH.pdf
House: NCOP
Language: ENG
Date: 2025-10-23
Type: HANSARD
File location: hansard/01mfgh4vvozjbsrxs7cjcladwfjsvz7hqp.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vvozjbsrxs7cjcladwfjsvz7hqp.pdf
Name: HAN-NA-2025-10-23-UH.pdf
House: NA
Language: ENG
Date: 2025-10-23
Type: HANSARD
File location: hansard/01mfgh4vvxqtprxbrwwvfjpdnbv2scaplm.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vvxqtprxbrwwvfjpdnbv2scaplm.pdf
Name: HAN-NA-2025-10-22-UH.pdf
House: NA
Language: ENG
Date: 2025-10-22
Type: HANSARD
File location: hansard/01mfgh4vrtjtzfqy7navh2qi4ddzlmluu3.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vrtjtzfqy7navh2qi4ddzlmluu3.pdf
Name: HAN-NA-2025-10-21-UH.pdf
House: NA
Language: ENG
Date: 2025-10-21
Type: HANSARD
File location: hansard/01mfgh4vuz4vdknbmtunhyfbxirpfiwnog.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vuz4vdknbmtunhyfbxirpfiwnog.pdf
Name: HAN-NCOP-2025-10-16-UH.pdf
House: NCOP
Language: ENG
Date: 2025-10-16
Type: HANSARD
File location: hansard/01mfgh4vsl2ltoejdkifb375lsscqp2rli.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vsl2ltoejdkifb375lsscqp2rli.pdf
Name: HAN-NCOP-2025-10-15-UH.pdf
House: NCOP
Language: ENG
Date: 2025-10-15
Type: HANSARD
File location: hansard/01mfgh4vqilpl3236oufgkfglh7yrpg33j.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vqilpl3236oufgkfglh7yrpg33j.pdf
Name: HAN-NCOP-2025-10-14-UH.pdf
House: NCOP
Language: ENG
Date: 2025-10-14
Type: HANSARD
File location: hansard/01mfgh4vresutnnqaxung3ogjlj4czmep7.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vresutnnqaxung3ogjlj4czmep7.pdf
Name: HAN-NCOP-2025-10-09-UH.pdf
House: NCOP
Language: ENG
Date: 2025-10-09
Type: HANSARD
File location: hansard/01mfgh4vrfbgtossecjvdiosv4jfv6tjay.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vrfbgtossecjvdiosv4jfv6tjay.pdf
Name: HAN-NA-CP-2025-10-09-UH.pdf
House: NA
Language: ENG
Date: 2025-10-09
Type: HANSARD
File location: hansard/01mfgh4vvyd6u6cvu7gjek52flb5o6dve2.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vvyd6u6cvu7gjek52flb5o6dve2.pdf
Name: HAN-NCOP-2025-10-07-UH.pdf
House: NCOP
Language: ENG
Date: 2025-10-07
Type: HANSARD
File location: hansard/01mfgh4vtkxs5n3lijorf2hmo3urssmp43.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vtkxs5n3lijorf2hmo3urssmp43.pdf
Name: HAN-NCOP-2025-09-26-UH.pdf
House: NCOP
Language: ENG
Date: 2025-09-26
Type: HANSARD
File location: hansard/01mfgh4vt3jfdqet7yvra3rcbsuabz75ak.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vt3jfdqet7yvra3rcbsuabz75ak.pdf
Name: HAN-MPS-NA(1)-2025-09-19-UH.pdf
House: NA
Language: ENG
Date: 2025-09-19
Type: HANSARD
File location: hansard/01mfgh4vwcfmimjvdn65ektsgg4ts3253n.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vwcfmimjvdn65ektsgg4ts3253n.pdf
Name: HAN-MPS-NA(2)-2025-09-19-UH.pdf
House: NA
Language: ENG
Date: 2025-09-19
Type: HANSARD
File location: hansard/01mfgh4vvueefa6er7ojf3ltgyeb4cuavn.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vvueefa6er7ojf3ltgyeb4cuavn.pdf
Name: HAN-NA-2025-09-18-UH.pdf
House: NA
Language: ENG
Date: 2025-09-18
Type: HANSARD
File location: hansard/01mfgh4vvi3dd2a7jnvvfyu5mohns2g3mt.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vvi3dd2a7jnvvfyu5mohns2g3mt.pdf
Name: HAN-NA-2025-09-17-UH.pdf
House: NA
Language: ENG
Date: 2025-09-17
Type: HANSARD
File location: hansard/01mfgh4vvopmedzdyhrjalgkmycx3eyf4y.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vvopmedzdyhrjalgkmycx3eyf4y.pdf
Name: HAN-NA-2025-09-16-UH.pdf
House: NA
Language: ENG
Date: 2025-09-16
Type: HANSARD
File location: hansard/01mfgh4vtyhua7u44ulnbyqlmluyhkniyx.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vtyhua7u44ulnbyqlmluyhkniyx.pdf
Name: HAN-MPS-NA(2)-2025-09-12-UH.pdf
House: NA
Language: ENG
Date: 2025-09-12
Type: HANSARD
File location: hansard/01mfgh4vq23g7ks3co2fej6h7kvofc7jdf.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vq23g7ks3co2fej6h7kvofc7jdf.pdf
Name: HAN-MPS-NA(3)-2025-09-12-UH.pdf
House: NA
Language: ENG
Date: 2025-09-12
Type: HANSARD
File location: hansard/01mfgh4vxm5hcbehxy5bbkpnuwxgxhtzll.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vxm5hcbehxy5bbkpnuwxgxhtzll.pdf
Name: HAN-MPS-NA(1)-2025-09-12-UH.pdf
House: NA
Language: ENG
Date: 2025-09-12
Type: HANSARD
File location: hansard/01mfgh4vunn5iu7apwuzglai76vqoj26it.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vunn5iu7apwuzglai76vqoj26it.pdf
Name: HAN-NCOP-2025-09-11-UH.pdf
House: NCOP
Language: ENG
Date: 2025-09-11
Type: HANSARD
File location: hansard/01mfgh4vvsfoe7yqfoqfek2igjyzsxv35m.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vvsfoe7yqfoqfek2igjyzsxv35m.pdf
Name: HAN-NA-2025-09-11-UH.pdf
House: NA
Language: ENG
Date: 2025-09-11
Type: HANSARD
File location: hansard/01mfgh4vxwxrnggtf4wnaj4feztuswh3nd.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vxwxrnggtf4wnaj4feztuswh3nd.pdf
Name: HAN-NCOP-2025-09-10-UH.pdf
House: NCOP
Language: ENG
Date: 2025-09-10
Type: HANSARD
File location: hansard/01mfgh4vu3rab65dqzarhi7va25pcwmrds.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vu3rab65dqzarhi7va25pcwmrds.pdf
Name: HAN-NA-2025-09-10-UH.pdf
House: NA
Language: ENG
Date: 2025-09-10
Type: HANSARD
File location: hansard/01mfgh4vw3sntjluq3d5al2gmutatrv4nr.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vw3sntjluq3d5al2gmutatrv4nr.pdf
Name: HAN-NA-2025-09-09-UH.pdf
House: NA
Language: ENG
Date: 2025-09-09
Type: HANSARD
File location: hansard/01mfgh4vvbnqy7e5a73be2jtf5vdxghp4e.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vvbnqy7e5a73be2jtf5vdxghp4e.pdf
Name: HAN-NCOP-2025-09-09-UH.pdf
House: NCOP
Language: ENG
Date: 2025-09-09
Type: HANSARD
File location: hansard/01mfgh4vr2po43tjtfpjck2brr3p7hoqle.pdf
PDF URL: https://www.parliament.gov.za/storage/app/media/Docs/hansard/01mfgh4vr2po43tjtfpjck2brr3p7hoqle.pdf
Name: HAN-NCOP-WP-2025-08-14-UH.pdf
House: NCOP
Language: ENG
Date: 2025-08-14
Type: HANSARD
File location: hansard/01mfgh4vuqsmd6qo3gt5b3qktf35dn6ysy.pdf

In [ ]:
 # ---- Read data back from Iceberg ----
rows = proceedings_table.scan().to_pandas()
rows

Empty DataFrame
Columns: [id, uvimba_id, document_name, house, language, date, document_type, file_location, pdf_url, pdf_text]
Index: []

In [ ]:
print("Files currently in proceedings folder:")

response = s3_client.list_objects_v2(
    Bucket=bucket_name,
    Prefix="proceedings/"
)

for obj in response.get("Contents", []):
    print(obj["Key"])

Files currently in proceedings folder:
proceedings/2327197.pdf
proceedings/2327199.pdf
proceedings/HAN-JNT-2026-02-19-UH.pdf.pdf
proceedings/HAN-JNT-2026-02-19-UH.pdf
proceedings/HAN-MPS-NA(2)-2026-03-06-UH.pdf.pdf
proceedings/HAN-MPS-NA(2)-2026-03-06-UH.pdf
proceedings/HAN-NA-2026-02-24-UH.pdf.pdf
proceedings/HAN-NA-2026-02-24-UH.pdf
proceedings/HAN-NA-2026-02-25-UH.pdf.pdf
proceedings/HAN-NA-2026-02-25-UH.pdf
proceedings/HAN-NA-2026-03-03-UH.pdf.pdf
proceedings/HAN-NA-2026-03-03-UH.pdf
proceedings/HAN-NA-2026-03-04-UH.pdf.pdf
proceedings/HAN-NA-2026-03-04-UH.pdf
proceedings/HAN-NA-2026-03-05-UH.pdf.pdf
proceedings/HAN-NA-2026-03-05-UH.pdf
proceedings/HAN-NCOP-2026-02-27-UH.pdf.pdf
proceedings/HAN-NCOP-2026-02-27-UH.pdf
proceedings/HAN-NCOP-2026-03-04-UH.pdf.pdf
proceedings/HAN-NCOP-2026-03-04-UH.pdf
proceedings/HAN-NCOP-2026-03-05-UH.pdf.pdf
proceedings/HAN-NCOP-2026-03-05-UH.pdf

# Bills
# Intialize Warehouse connection

In [ ]:
warehouse_path = "/content/warehouse"
s3_uri = "https://15c46705015d147b9bbf2d532ce26495.r2.cloudflarestorage.com"
catalog = rest.RestCatalog(
    name="default",
    warehouse="15c46705015d147b9bbf2d532ce26495_standard-deviants-storage",
    uri="https://catalog.cloudflarestorage.com/15c46705015d147b9bbf2d532ce26495/standard-deviants-storage",
    token=userdata.get('CLOUDFLARE_API_KEY'),
)
if not catalog.namespace_exists("default"):
  catalog.create_namespace("default")

table_name = "default.bills"


# Create table using PyArrow schema
bill_schema = pa.schema([
    ("bill_identifier", pa.int64()),
    ("title", pa.string()),
    ("bill_number", pa.string()),
    ("pdf_url", pa.string()),
    ("pdf_text", pa.string()),
    ])
if not catalog.table_exists(table_name):
  bill_table = catalog.create_table(table_name, schema=bill_schema)
else:
  bill_table = catalog.load_table(table_name)

def retrieve_bill_by_id(idents: list[str]):
  rows = bill_table.scan(row_filter=In("bill_identifier", idents)).to_pandas()
  return rows

ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=Exception('Connection closed while reading from the driver')>
Exception: Connection closed while reading from the driver

## Retrieve and load

In [ ]:
!pip install browserforge

Collecting browserforge
  Downloading browserforge-1.2.4-py3-none-any.whl.metadata (28 kB)
Collecting apify_fingerprint_datapoints (from browserforge)
  Downloading apify_fingerprint_datapoints-0.11.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from browserforge) (8.3.1)
Downloading browserforge-1.2.4-py3-none-any.whl (37 kB)
Downloading apify_fingerprint_datapoints-0.11.0-py3-none-any.whl (726 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 726.5/726.5 kB 38.3 MB/s eta 0:00:00
Installing collected packages: apify_fingerprint_datapoints, browserforge
Successfully installed apify_fingerprint_datapoints-0.11.0 browserforge-1.2.4

In [ ]:
!playwright install chromium

In [ ]:
!apt-get install -y poppler-utils tesseract-ocr
!pip install pdfplumber pdf2image pytesseract

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 124 not upgraded.
Need to get 186 kB of archives.
After this operation, 697 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.12 [186 kB]
Fetched 186 kB in 0s (2,433 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 122210 files and directories currently installed.)
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.12_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.12) ...
Setting up poppler-utils (22.02.0-2ubuntu0.12) ...
Processing triggers for man-db (2.10.2-1) ...
Collecting pdfplumber
  Downloading pdfplumber-0.11.9-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: pdf2image in /usr/local/lib/python3.12/dist-packages (1.17.0)
Requirement already satisfied: pytesseract in /usr/local/lib/python3.12/dist-packages (0.3.13)
Collecting pdfminer.six==20251230 (from pdfplumber)
  Downloading pdfminer_six-20251230-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-5.6.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.1/68.1 kB 8.2 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.5)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (26.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)
Downloading pdfplumber-0.11.9-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 7.4 MB/s eta 0:00:00
Downloading pdfminer_six-20251230-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 114.3 MB/s eta 0:00:00
Downloading pypdfium2-5.6.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 132.4 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20251230 pdfplumber-0.11.9 pypdfium2-5.6.0

In [ ]:
from scrapling.fetchers import StealthyFetcher
import requests
import pdfplumber
from pdf2image import convert_from_path
import pytesseract
import tempfile
import os
import re

def extract_pdf_text(url_or_path, is_url=True):
    """
    Extract PDF text using:
    - pdfplumber for initial extraction
    - OCR if text is empty or contains '(cid:'
    - fitz as fallback for normal pages
    """
    # Get PDF bytes
    if is_url:
        pdf_bytes = requests.get(url_or_path).content
    else:
        with open(url_or_path, "rb") as f:
            pdf_bytes = f.read()

    text_output = ""

    # First attempt: pdfplumber + OCR
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for i, page in enumerate(pdf.pages):


            page_text = page.extract_text()
            page_text_str = page_text if page_text else ""

            # Decide if OCR is needed
            if not page_text_str.strip() or '(cid:' in page_text_str:
                print(f"Page {i + 1} needs OCR...")

                images = convert_from_bytes(pdf_bytes, first_page=i+1, last_page=i+1, dpi=300)
                ocr_text = ""
                for img in images:
                    ocr_text += pytesseract.image_to_string(img) + "\n\n"

                page_text_str = ocr_text
            else:
                # fallback: use fitz for better normal text extraction
                doc = fitz.open(stream=pdf_bytes, filetype="pdf")
                fitz_page_text = doc[i].get_text()
                if fitz_page_text:
                    page_text_str = fitz_page_text

            # Clean spacing
            page_text_str = re.sub(r'\n+', '\n', page_text_str)                  # reduce multiple newlines
            page_text_str = re.sub(r' +', ' ', page_text_str)                    # reduce multiple spaces
            page_text_str = re.sub(r'([a-z])([A-Z])', r'\1 \2', page_text_str)  # fix missing spaces

            text_output += page_text_str.strip() + "\n\n"

    return text_output


start_bill_id = 1205
end_bill_id = 1335

StealthyFetcher.adaptive = True

documents = {}

for bill_id in range(start_bill_id, end_bill_id + 1):

    url = f"https://pmg.org.za/bill/{bill_id}/"

    p = await StealthyFetcher.async_fetch(
        url,
        headless=True,
        network_idle=True
    )

    article = p.css("article.page")[0]

    h1 = article.css("h1")[0]
    title_tag = p.css("title")[0].text.strip()

    title = title_tag.replace(" | PMG", "")

    bill_number = h1.css("span.text-muted")[0].text.strip()


    full_text = title.strip()

    title = full_text.replace(bill_number, "").strip()

    print("Bill ID:", bill_id)
    print("Title:", title)
    print("Bill Number:", bill_number)

    # find PDF
    pdf_links = article.css("a[href$='.pdf']")

    for link in pdf_links:
        pdf_url = link.attrib.get("href")

        print("PDF URL:", pdf_url)

        text = extract_pdf_text(pdf_url)

        print("\n----- PDF TEXT PREVIEW -----\n")
        print(text[:1000])
        print("\n----------------------------\n")

        filename = f"bill_{bill_id}_text.txt"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(text)

        documents[bill_id] = {
            "bill_identifier": bill_id,
            "title": title,
            "bill_number": bill_number,
            "pdf_url": pdf_url,
            "pdf_text": text
        }

        break

if documents:
    df = pd.DataFrame(documents.values())
    # Convert to PyArrow and append to Iceberg
    arrow_table = pa.Table.from_pandas(df)
    bill_table.append(arrow_table)

    print(f"{len(df)} bills inserted into Iceberg table.")

    # ---- Read data back from Iceberg table ----
    rows = bill_table.scan().to_pandas()

    print("\nData currently in Iceberg table:\n")
    print(rows)

[2026-03-16 14:06:50] INFO: Fetched (200) <GET https://pmg.org.za/bill/1205/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1205/> (referer: https://www.google.com/)

Bill ID: 1205
Title: National State Enterprises Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/State_Enterprise_Bill.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za
STAATSKOERANT, 9 Januarie 2024
No. 49978    11
DEPARTMENT OF PUBLIC ENTERPRISES
NO. 4242
9 January 2024

This gazette is also available free online at www.gpwonline.co.za
12    No. 49978
GOVERNMENT GAZETTE, 9 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 9 Januarie 2024
No. 49978    13

This gazette is also available free online at www.gpwonline.co.za
14    No. 49978
GOVERNMENT GAZETTE, 9 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 9 Januarie 2024
No. 49978    15

This gazette is also available free online at www.gpwonline.co.za
16    No. 49978
GOVERNMENT GAZETTE, 9 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 9 Januarie 2024
No. 49978    17

This gazette is also available free online at www.gpwonline.co.za
18    No. 49978
GOVERNMENT GAZETTE, 9 January 2024



----------------------------

[2026-03-16 14:06:58] INFO: Fetched (200) <GET https://pmg.org.za/bill/1206/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1206/> (referer: https://www.google.com/)

Bill ID: 1206
Title: Repeal of the South African Airways Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/SAA.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 9 Januarie 2024
No. 49978    3
Government Notices • Goewermentskennisgewings
DEPARTMENT OF PUBLIC ENTERPRISES
NO. 4241
9 January 2024

This gazette is also available free online at www.gpwonline.co.za
4    No. 49978
GOVERNMENT GAZETTE, 9 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 9 Januarie 2024
No. 49978    5

This gazette is also available free online at www.gpwonline.co.za
6    No. 49978
GOVERNMENT GAZETTE, 9 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 9 Januarie 2024
No. 49978    7

This gazette is also available free online at www.gpwonline.co.za
8    No. 49978
GOVERNMENT GAZETTE, 9 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 9 Januarie 2024
No. 49978    9

This gazette is also available free online at www.gpwonline.co.za
10    No. 49

----------------------------

[2026-03-16 14:07:06] INFO: Fetched (200) <GET https://pmg.org.za/bill/1207/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1207/> (referer: https://www.google.com/)

Bill ID: 1207
Title: Gas Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/Mineral_Resources_and_Energy_Department_of_-_Mineraalbronne_en_Energie_Departement_20240119-GGN-50009-04256-02-2-65.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za
34    No. 50009
GOVERNMENT GAZETTE, 19 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 19 Januarie 2024
No. 50009    35

This gazette is also available free online at www.gpwonline.co.za
36    No. 50009
GOVERNMENT GAZETTE, 19 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 19 Januarie 2024
No. 50009    37

This gazette is also available free online at www.gpwonline.co.za
38    No. 50009
GOVERNMENT GAZETTE, 19 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 19 Januarie 2024
No. 50009    39

This gazette is also available free online at www.gpwonline.co.za
40    No. 50009
GOVERNMENT GAZETTE, 19 January 2024

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 19 Januarie 2024
No. 50009    41

This gazette is also available free online at ww

----------------------------

[2026-03-16 14:07:13] INFO: Fetched (200) <GET https://pmg.org.za/bill/1208/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1208/> (referer: https://www.google.com/)

Bill ID: 1208
Title: National State Enterprises Bill
Bill Number: (B1-2024)
PDF URL: https://pmg.org.za/files/B1-2024_National_State_Enterprises.pdf
Page 31 needs OCR...

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA
NATIONAL STATE
ENTERPRISES BILL
(As introduced in the National Assembly (proposed section 75); explanatory summary of Bill
and prior notice of its introduction published in Government Gazette No. 49978 of
9 January 2024)
(The English text is the offıcial text of the Bill)
(MINISTER OF PUBLIC ENTERPRISES)
[B 1—2024]
ISBN 978-1-4850-0961-0
No. of copies printed ....................................... 250

BILL
To provide for the development of a strategy for national state enterprises; to
establish the State Asset Management SOC Ltd; to provide for the State as the sole
shareholder of a holding company; to consolidate the State’s shareholdings in
national state enterprises; to provide for the powers of the shareholder on behalf of
the State; to provide for the phased succession of national state enterprises to the
holding company; to provide for the holding company’s powers as shareholder of
subsidiaries; to provide for appropriate and effective monitoring and re

----------------------------

[2026-03-16 14:07:23] INFO: Fetched (200) <GET https://pmg.org.za/bill/1209/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1209/> (referer: https://www.google.com/)

Bill ID: 1209
Title: Repeal of South African Airways Bill
Bill Number: (B2-2024)
PDF URL: https://pmg.org.za/files/B2-2024_Repeal_of_South_African_Airways.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA
REPEAL OF
SOUTH AFRICAN AIRWAYS BILL
(As introduced in the National Assembly (proposed section 75); explanatory summary of
Bill and prior notice of its introduction published in Government Gazette No. 49978
of 9 January 2024)
(The English text is the offıcial text of the Bill)
(MINISTER OF PUBLIC ENTERPRISES)
[B 2—2024]
ISBN 978-1-4850-0962-7
No. of copies printed .........................................150

BILL
To repeal the South African Airways Act, 2007; and to provide for matters
connected therewith.
B
E IT ENACTED by the Parliament of the Republic of South Africa, as follows:—
Deﬁnitions
1. In this Act, unless the context indicates otherwise—
‘‘company’’ means South African Airways Limited, a public company duly
incorporated in terms of the Companies Act, or its successor in title; and
‘‘Shareholder Representative’’ means the Cabinet Member designated in terms
of section 3(2).
Repeal of Act 5 of 2007
2. The South African Airways Act, 2007 (Act No. 5 of

----------------------------

[2026-03-16 14:07:29] INFO: Fetched (200) <GET https://pmg.org.za/bill/1210/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1210/> (referer: https://www.google.com/)

Bill ID: 1210
Title: Pension Funds Amendment Bill
Bill Number: (B3-2024)
PDF URL: https://pmg.org.za/files/50968_23-7_PensionsFundAmendmentAct31_2024.pdf
Page 2 needs OCR...
Page 3 needs OCR...

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 709
23 July 2024
No. 50968
Cape Town
Kaapstad
No. 5052
No. 5052
23 July 2024
23 Julie 2024
Hierby word bekend gemaak dat die
President sy goedkeuring geheg het
aan die onderstaande Wet wat hierby ter
algemene inligting gepubliseer word:—
The Presidency
DIE PRESIDENSIE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No. 31 of 2024: Pension Funds
Amendment Act, 2024
No. 31 van 2024: Wysigingswet op
Pensioenfondse, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 0 9 6 8
i SSN 1682-5845

2 No. 50968 GOVERNMENT GAZETTE, 23 JULY 2024
Act No. 31 of 2024 Pension Funds Amendment Act, 2024
GENERAL EXPLANATORY NOTE:
[ ] Words in bold type in square brackets indicate omissions from
existing enactments.
Words underlined with a solid line indicate insertions in
existing enactments.


(English text signed by the Presi

----------------------------

[2026-03-16 14:07:51] INFO: Fetched (200) <GET https://pmg.org.za/bill/1211/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1211/> (referer: https://www.google.com/)

Bill ID: 1211
Title: Division of Revenue Bill
Bill Number: (B4-2024)
PDF URL: https://pmg.org.za/files/50743_03-06_DivisionofRevenueAct_24_2024.pdf
Page 96 needs OCR...
Page 106 needs OCR...
Page 110 needs OCR...

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 708
3 June 2024
No. 50743
Cape Town
Kaapstad
No. 4921
No. 4921
3 June 2024
3 Junie 2024
Esi
sisaziso
sokuba
u Mongameli
uwamkele
lo
mthetho
ulandelayo
nonikezelwa
kuluntu
jikelele
kolu
xwebhu:—
The Presidency
OFISI KAMONGAMELI
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No. 24 of 2024: The Division of
Revenue Act, 2024
Ino 24 ka 2024: Umthetho wolwabiwo
Iwengeniso, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 0 7 4 3
i SSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 50743
GOVERNMENT GAZETTE, 3 June 2024
Act No. 24 of 2024
The Division of Revenue Act, 2024
ACT
To provide for the equitable division of revenue raised nationally among the
national, provincial and local spheres of government for the 2024/25 ﬁnancial year;
the determination of each prov

----------------------------

[2026-03-16 14:08:37] INFO: Fetched (200) <GET https://pmg.org.za/bill/1212/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1212/> (referer: https://www.google.com/)

Bill ID: 1212
Title: Appropriation Bill
Bill Number: (B5-2024)
PDF URL: https://pmg.org.za/files/51101_ApproprriationAct40_2024.pdf
Page 5 needs OCR...
Page 7 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Page 14 needs OCR...
Page 15 needs OCR...
Page 16 needs OCR...
Page 17 needs OCR...
Page 18 needs OCR...
Page 19 needs OCR...
Page 20 needs OCR...
Page 21 needs OCR...
Page 22 needs OCR...
Page 23 needs OCR...
Page 24 needs OCR...
Page 25 needs OCR...
Page 26 needs OCR...
Page 27 needs OCR...
Page 28 needs OCR...
Page 29 needs OCR...
Page 30 needs OCR...
Page 31 needs OCR...
Page 32 needs OCR...
Page 33 needs OCR...
Page 34 needs OCR...
Page 35 needs OCR...
Page 36 needs OCR...
Page 37 needs OCR...
Page 38 needs OCR...
Page 39 needs OCR...
Page 40 needs OCR...
Page 41 needs OCR...
Page 42 needs OCR...
Page 43 needs OCR...
Page 44 needs OCR...
Page 45 needs OCR...
Page 46 needs OCR...
Page 47 needs OCR...
Page 48 needs OCR...
Page 49 needs OCR...
Page 50 needs OCR...
Page 51 needs OCR...
Page 52 needs OCR...
Page 53 needs OCR...
Page 54 needs OCR...
Page 55 needs OCR...
Page 56 needs OCR...
Page 57 needs OCR...
Page 58 needs OCR...
Page 59 needs OCR...
Page 60 needs OCR...
Page 61 needs OCR...
Page 62 needs OCR...
Page 63 needs OCR...
Page 64 needs OCR...
Page 65 needs OCR...
Page 66 needs OCR...
Page 67 needs OCR...
Page 68 needs OCR...
Page 69 needs OCR...
Page 70 needs OCR...
Page 71 needs OCR...
Page 72 needs OCR...
Page 73 needs OCR...
Page 74 needs OCR...
Page 75 needs OCR...
Page 76 needs OCR...
Page 77 needs OCR...
Page 79 needs OCR...
Page 80 needs OCR...
Page 81 needs OCR...
Page 82 needs OCR...
Page 83 needs OCR...

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 710
20 Augustus 2024
No. 51101
Cape Town
Kaapstad
No. 5140
No. 5140
20 Augustus 2024
20 August 2024
Go itsisiwe gore Moporesidente o
dumetse Molao o o latelang, o o
phasaladiwang fano go itsisiwe botlhe:—
The Presidency
MOPORESIDENTE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No. 40 of 2024: Appropriation Act,
Act 2024
No. 40 ya 2024: Molao wa Tekanyetso, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 1 0 1
Iss N 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51101
GOVERNMENT GAZETTE, 20 Augustus 2024
Act No. 40 of 2024
Appropriation Act, Act 2024
ACT
To appropriate money from the National Revenue Fund for the requirements of the
State for the 2024/25 ﬁnancial year; to prescribe conditions for the spending of
funds withdrawn for the 2025/26 ﬁnancial year befor

----------------------------

[2026-03-16 14:15:08] INFO: Fetched (200) <GET https://pmg.org.za/bill/1213/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1213/> (referer: https://www.google.com/)

Bill ID: 1213
Title: Second Adjustments Appropriation (2023/24 Financial Year) Bill
Bill Number: (B6-2024)
PDF URL: https://pmg.org.za/files/50625_7-5_Second_Adjustments_Appropriation_Act_18_2024.pdf
Page 7 needs OCR...

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 707
7 May 2024
No. 50625
Cape Town
Kaapstad
No. 4791
No. 4791
7 May 2024
7 Mei 2024
Mona ho tsebiswa hore Mopresidente
o amohetse Molao ona o latelang, o
phatlalatswang mona bakeng sa tsebiso
ya setjhaba ka bophara:—
The Presidency
OFISI YA MOPORESIDENTE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No.18 of 2024: Second Adjustments
Appropriation (2023/24 Financial Year),
Act 2024
Act No. 18 ya 2024: Molao wa Diphetoho
tsa bobedi tsa kabo (Selemo sa ditjhelete
sa 2023/24)
9
7 7 1 6 8 2 5 8 4 0 0 3
5 0 6 2 5
i SSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 50625
GOVERNMENT GAZETTE, 7 May 2024
Act No.18 of 2024
Second Adjustments Appropriation (2023/24 Financial Year), Act 2024
ACT
To effect adjustments to the appropriation of money from the Nat

----------------------------

[2026-03-16 14:15:19] INFO: Fetched (200) <GET https://pmg.org.za/bill/1214/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1214/> (referer: https://www.google.com/)

Bill ID: 1214
Title: Gold and Foreign Exchange Contingency Reserve Account Defrayal Amendment Bill
Bill Number: (B7-2024)
PDF URL: https://pmg.org.za/files/18a662_897b223e2b6045fca6cd47a8d86c16c7.pdf

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 708
13 June 2024
No. 50814
Cape Town
Kaapstad
No. 4964
No. 4964
13 June 2024
13 Junie 2024
Ngalokhu
kwaziswa
ukuthi
u Mongameli
usewuvumile
lo Mthetho
nosewuzoshicilelelwa umphakathi:—
The Presidency
IHHOVISI LIKAMONGAMELI
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No. 27 of 2024: Gold and Foreign
Exchange
Contingency
Reserve
Account Defrayal Amendment Act,
2024
No. 27 Ka 2024: Umthetho-sihlomelo
we-akhawunti
egcinelwe
okungehla
kwigolide
norhwebo-mali
namanye
amazwe, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 0 8 1 4
i SSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 50814
GOVERNMENT GAZETTE, 13 June 2024
Act No. 27 of 2024
Gold and Foreign Exchange Contingency Reserve Account Defrayal Amendment Act, 2024
GENERAL EXPLANATORY NOTE:
[
]
Word

----------------------------

[2026-03-16 14:15:25] INFO: Fetched (200) <GET https://pmg.org.za/bill/1215/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1215/> (referer: https://www.google.com/)

Bill ID: 1215
Title: Revenue Laws Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240221Draft_Revenue_Laws_Amendment_Bill_2024.pdf

----- PDF TEXT PREVIEW -----

DRAFT
REVENUE LAWS SECOND AMENDMENT BILL





21 February 2024

DRAFT


2


GENERAL EXPLANATORY NOTE:
[
]
Words in bold type in square brackets indicate omissions from existing
enactments.
_______
Words underlined with a solid line indicate insertions in existing
enactments.


BILL

To amend the Income Tax Act, 1962, so as to amend certain definitions; to
amend certain provisions; to amend certain Schedules; and to provide for
matters connected therewith.

BE IT ENACTED by the Parliament of the Republic of South Africa, as follows:—

DRAFT


3
Amendment of section 1 of Act 58 of 1962, as amended by section 3 of Act 90
of 1962, section 1 of Act 6 of 1963, section 4 of Act 72 of 1963, section 4 of Act
90 of 1964, section 5 of Act 88 of 1965, section 5 of Act 55 of 1966, section 5 of
Act 76 of 1968, section 6 of Act 89 of 1969, section 6 of Act 52 of 1970, section
4 of Act 88 of 1971, section 4 of Act 90 of 1972, section 4 of Act 65 of 1973,
section 4 o

----------------------------

[2026-03-16 14:15:33] INFO: Fetched (200) <GET https://pmg.org.za/bill/1216/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1216/> (referer: https://www.google.com/)

Bill ID: 1216
Title: Global Minimum Tax Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240221DraftGMTBill.pdf

----- PDF TEXT PREVIEW -----

DRAFT
REPUBLIC OF SOUTH AFRICA
__________


DRAFT GLOBAL MINIMUM TAX BILL




____________

(As introduced in the National Assembly (proposed section 77))
(The English text is the official text of the Bill)

______________




(MINISTER OF FINANCE)






21 February 2024

2

DRAFT






BILL


The Bill proposes to introduce by reference the Global Anti-Base Erosion (Glo BE) Rules
in South Africa. The Glo BE Rules are a global minimum tax developed by the OECD/G20
Inclusive Framework on Base Erosion and Profit Shifting (BEPS), which is led by the
Organisation for Economic Co-operation and Development (OECD) and to provide for
matters connected therewith.

To provide for the imposition of top-up tax and to provide for matters connected
therewith.

PREAMBLE

SINCE the Organisation for Economic Co-operation and Development has established an
Inclusive Framework to counter BEPS;

AND SINCE the OECD/G20 Inclusive Framework on BEPS develope

----------------------------

[2026-03-16 14:15:40] INFO: Fetched (200) <GET https://pmg.org.za/bill/1217/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1217/> (referer: https://www.google.com/)

Bill ID: 1217
Title: Global Minimum Tax Administration Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240221GTAdBill.pdf

----- PDF TEXT PREVIEW -----

DRAFT

REPUBLIC OF SOUTH AFRICA
__________

DRAFT GLOBAL MINIMUM TAX
ADMINISTRATION BILL

____________

(As introduced in the National Assembly (proposed section 76)
(The English text is the official text of the Bill)

______________


(MINISTER OF FINANCE)




21 February 2024

DRAFT

BILL

The Bill proposes to introduce by reference the administrative provisions of the Global
Anti-Base Erosion (Glo BE) Model Rules in South Africa for purposes of the
administration of the Global Minimum Tax Bill.

ARRANGEMENT OF SECTIONS
1. Definitions
2. Obligation to submit Glo BE Information Return
3. Due date for submission of Glo BE Information Return
4. Exception for returns provided under automatic exchange of information agreement
5. Due date for payment
6. Refunds
7. Interest
8. Penalties
9. Records keeping and expiry of period of limitations
10. Elections
11. Administration of the Act
12. Regulations
13. Short title and commencement

DRAFT


E IT

----------------------------

[2026-03-16 14:15:45] INFO: Fetched (200) <GET https://pmg.org.za/bill/1218/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1218/> (referer: https://www.google.com/)

Bill ID: 1218
Title: Immigration Amendment Bill
Bill Number: (B8-2024)
PDF URL: https://pmg.org.za/files/B8-2024_Immigration_Amendment_Bill.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA
IMMIGRATION
AMENDMENT BILL
(As introduced in the National Assembly (proposed section 75); explanatory summary of
Bill and prior notice of its introduction published in Government Gazette No. 50310 of
19 March 2024)
(The English text is the offıcial text of the Bill)
(MINISTER OF HOME AFFAIRS)
[B 8—2024]
ISBN 978-1-4850-0984-9
No. of copies printed .........................................150

GENERAL EXPLANATORY NOTE:
[
]
Words in bold type in square brackets indicate omissions from
existing enactments.
Words underlined with a solid line indicate insertions in
existing enactments.
BILL
To amend the Immigration Act, 2002, so as to revise provisions relating to arrest
and detention of illegal foreigners for purposes of deportation and to align these
provisions with constitutional principles; and to provide for matters connected
therewith.
B
E IT ENACTED by the Parliament of the Republic of South Africa, as follows:—
Amendment of section 34 of Act 13 of 2002, as a

----------------------------

[2026-03-16 14:15:51] INFO: Fetched (200) <GET https://pmg.org.za/bill/1219/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1219/> (referer: https://www.google.com/)

Bill ID: 1219
Title: Local Government: Municipal Structures Amendment Bill
Bill Number: (B9-2024)
PDF URL: https://pmg.org.za/files/B9-2024_Municipal_Structures_Amendment_Bill.pdf
Page 6 needs OCR...
Page 7 needs OCR...

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA
LOCAL GOVERNMENT:
MUNICIPAL STRUCTURES
AMENDMENT BILL
(As introduced in the National Assembly (proposed section 75); explanatory summary of
Bill and prior notice of its introduction published in Government Gazette No. 48311 of
24 March 2023)
(The English text is the offıcial text of the Bill)
(MS S GWARUBE, MP)
[B 9—2024]
ISBN 978-1-4850-0985-6
No. of copies printed .........................................150

GENERAL EXPLANATORY NOTE:
[
]
Words in bold type in square brackets indicate omissions from
existing enactments.
Words underlined with a solid line indicate insertions in
existing enactments.
BILL
To amend the Local Government: Municipal Structures Act, 1998, so as to limit the
frequency in terms of which a motion to remove a speaker from office may be
tabled; to provide for circumstances when tabling of a motion for the removal of a
speaker from office will not be limited; to limit the frequency in terms of which a
motion to remove a whip from office ma

----------------------------

[2026-03-16 14:15:58] INFO: Fetched (200) <GET https://pmg.org.za/bill/1220/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1220/> (referer: https://www.google.com/)

Bill ID: 1220
Title: Local Government: Municipal Structures Second Amendment Bill
Bill Number: (B10-2024)
PDF URL: https://pmg.org.za/files/B10-2024__Municipal_Structures_2nd_Amendment_Bill.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA
LOCAL GOVERNMENT:
MUNICIPAL STRUCTURES
SECOND AMENDMENT BILL
(As introduced in the National Assembly (proposed section 75); explanatory summary of
Bill and prior notice of its introduction published in Government Gazette No. 48442 of
14 April 2023; Bill published in terms of section 154(2) of the Constitution in Government
Gazette No. 49603 of 3 November 2023)
(The English text is the offıcial text of the Bill)
(MS S GWARUBE, MP)
[B 10—2024]
ISBN 978-1-4850-0986-3
No. of copies printed .........................................150

GENERAL EXPLANATORY NOTE:
Words underlined with a solid line indicate insertions in
existing enactments.
BILL
To amend the Local Government: Municipal Structures Act, 1998, so as to extend
the time period within which a local council must appoint its representatives to the
district council; to extend the time period within which the ﬁrst meeting of the
council must be called after it has been declared elected so as to in turn provide


----------------------------

[2026-03-16 14:16:03] INFO: Fetched (200) <GET https://pmg.org.za/bill/1221/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1221/> (referer: https://www.google.com/)

Bill ID: 1221
Title: Remote Gambling Bill
Bill Number: (B11-2024)
PDF URL: https://pmg.org.za/files/B11-2024_Remote_Gambling.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA
REMOTE GAMBLING BILL
(As introduced in the National Assembly (proposed section 76);
explanatory summary of Bill and prior notice of its introduction published in Government
Gazette No. 46847 of 2 September 2022)
(The English text is the offıcial text of the Bill)
(MR DEAN MACPHERSON, MP)
[B 11—2024]
ISBN 978-1-4850-0987-0
No. of copies printed .........................................150

BILL
To provide for the regulation and licensing of remote gambling in the Republic of
South Africa; to provide for uniform norms and standards in respect of remote
gambling to be applicable throughout the Republic; to prevent and protect minors
and vulnerable persons from being exposed to the negative effects of gambling; to
ensure compliance with the Financial Intelligence Centre Act; to provide for the
protection of players; to protect the public and licensed remote gambling operators
from fraud and criminal behaviour, money laundering or ﬁnancing of terrorist and
related a

----------------------------

[2026-03-16 14:16:15] INFO: Fetched (200) <GET https://pmg.org.za/bill/1222/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1222/> (referer: https://www.google.com/)

Bill ID: 1222
Title: Electronic Deeds Registration Systems Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240424electronicdeedsregistrationsystemamenddraftbill.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za
4    No. 50539
GOVERNMENT GAZETTE, 24 April 2024
REPUBLIC OF SOUTH AFRICA



ELECTRONIC DEEDS REGISTRATION SYSTEMS AMENDMENT BILL, 2024


_________________

(As introduced in the National Assembly as a section 75 Bill; Bill published in
Government Gazette No. of )(The English text is the official text of the
Bill)
__________________



(MINISTER OF AGRICULTURE, LAND REFORM AND RURAL DEVELOPMENT)

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 24 April 2024
No. 50539    5
GENERAL EXPLANATORY NOTE:

[ ]
Words in bold type in square brackets indicate omissions from
existing enactments.
___________
Words underlined with a solid line indicate insertions in existing
enactments.
___________________________________________________________________

BILL

To amend the Electronic Deeds Registration Systems Act, 2019, so as to provide
that a client copy of a register

----------------------------

[2026-03-16 14:16:23] INFO: Fetched (200) <GET https://pmg.org.za/bill/1223/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1223/> (referer: https://www.google.com/)

Bill ID: 1223
Title: Construction Industry Development Board Amendment Draft Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240503draftconstructionindustrydevelopment-2-2.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za
186    No. 50608
GOVERNMENT GAZETTE, 3 May 2024

REPUBLIC OF SOUTH AFRICA



CONSTRUCTION INDUSTRY DEVELOPMENT BOARD AMENDMENT BILL
(As introduced in the National Assembly (proposed section 76); explanatory
summary of Bill and prior notice of its introduction published in Government Gazette
No. 50608 of 3-5-2024) (The English Text is the official text of the Bill)
-----------------------------------

(MINISTER OF PUBLIC WORKS AND INFRASTRUCTURE)




[B — 2022]

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 3 Mei 2024
No. 50608    187
2

090422lt

GENERAL EXPLANATORY NOTE:

[
]
Words in bold type in square brackets indicate omissions


from existing enactments.
___________
Words underlined with a solid line indicate insertions in existing
enactments.
___________________________________________________________________
BILL

To amend the Construction Ind

----------------------------

[2026-03-16 14:16:32] INFO: Fetched (200) <GET https://pmg.org.za/bill/1224/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1224/> (referer: https://www.google.com/)

Bill ID: 1224
Title: Children's Amendment Bill
Bill Number: (X-2023)
PDF URL: https://pmg.org.za/files/240514early-childhood-development-3-3.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 14 Mei 2024
No. 50648    5

REPUBLIC OF SOUTH AFRICA





CHILDREN'S AMENDMENT BILL, 2023



-------------------------------

(As introduced in the National Assembly (proposed section 76); explanatory
summary of Bill published in Government Gazette No. of ) (The English text is the
official text of the Bill)

---------------------------------

This gazette is also available free online at www.gpwonline.co.za
6    No. 50648
GOVERNMENT GAZETTE, 14 May 2024

(MINISTER OF BASIC EDUCATION)

[B — 2023]
GENERAL EXPLANATORY NOTE:

[ ]
Words in bold type in square brackets indicate omissions from
existing enactments.
___________
Words underlined with a solid line indicate insertions in existing
enactments.
___________________________________________________________________

BILL

To amend the Children's Act, 2005, so as to insert new provisions to further
provide for the requir

----------------------------

[2026-03-16 14:16:40] INFO: Fetched (200) <GET https://pmg.org.za/bill/1225/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1225/> (referer: https://www.google.com/)

Bill ID: 1225
Title: Local Government: General Laws Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240514generallawsamendbilldraft-4-4.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za
4    No. 50650
GOVERNMENT GAZETTE, 14 May 2024
2

REPUBLIC OF SOUTH AFRICA







LOCAL GOVERNMENT: GENERAL LAWS AMENDMENT BILL, 2024




--------------------------------
(As introduced in the National Assembly (proposed section 76); explanatory
summary of Bill published in Government Gazette No. ----of----) (The English text is
the official text of the Bill)
---------------------------------




(MINISTER OF COOPERATIVE GOVERNANCE AND TRADITIONAL AFFAIRS)





[B ─ 2024]

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 14 Mei 2024
No. 50650    5
3

GENERAL EXPLANATORY NOTE:

[ ]
Words in bold type in square brackets indicate omissions from
existing enactments.
____________
Words underlined with a solid line indicate insertions in existing
enactments.
___________________________________________________________________

To amend—
• the Local G

----------------------------

[2026-03-16 14:16:49] INFO: Fetched (200) <GET https://pmg.org.za/bill/1226/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1226/> (referer: https://www.google.com/)

Bill ID: 1226
Title: Local Government: Municipal Structures Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240521Municipal_Structures_Amendment_Bill-4-4.pdf
Page 1 needs OCR...
Page 2 needs OCR...
Page 3 needs OCR...
Page 4 needs OCR...
Page 5 needs OCR...
Page 6 needs OCR...
Page 7 needs OCR...
Page 8 needs OCR...
Page 9 needs OCR...
Page 10 needs OCR...
Page 11 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...

----- PDF TEXT PREVIEW -----

4 No. 50682 GOVERNMENT GAZETTE, 21 MAY 2024
REPUBLIC OF SOUTH AFRICA
LOCAL GOVERNMENT: MUNICIPAL STRUCTURES AMENDMENT BILL
(As introduced in the National Assembly (proposed section 76); explanatory
summary of Bill and prior notice of its introduction published in Government
Gazette No. 50682 of 21 May 2024) (The English text is the official text of the Bill)
(MINISTER OF COOPERATIVE GOVERNANCE AND TRADITIONAL AFFAIRS)
[B — 2024]
This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 21 MEI 2024 No. 50682 5
GENERAL EXPLANATORY NOTE:
[ ] Words in bold type in square brackets indicate omissions
from existing enactments.
Words underlined with a solid line indicates insertions in
existing enactments.
To amend the Local Government: Municipal Structures Act, 1998 so as to insert
the definition for coalition agreement; to change municipalities with a mayoral
executive system, in which no party obtained a majority of seats, to a collective
executive system within a pr

----------------------------

[2026-03-16 14:17:35] INFO: Fetched (200) <GET https://pmg.org.za/bill/1227/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1227/> (referer: https://www.google.com/)

Bill ID: 1227
Title: National Environmental Management: Biodiversity Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240524nelmbiodiversitybill.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 24 Mei 2024
No. 50706    5

SCHEDULE

REPUBLIC OF SOUTH AFRICA



NATIONAL ENVIRONMENTAL MANAGEMENT: BIODIVERSITY BILL



__________________

(As introduced in the National Assembly (proposed section 76); explanatory
summary of Bill published in Government Gazette No. … of … 2024)
(The English text is the official text of the Bill)
__________________




(MINISTER OF FORESTRY, FISHERIES AND THE ENVIRONMENT)





[B—2024]

This gazette is also available free online at www.gpwonline.co.za
6    No. 50706
GOVERNMENT GAZETTE, 24 May 2024
BILL

To provide for the management and conservation of the Republic’s
biodiversity within the framework of the National Environmental Management
Act, 1998; to provide for the South African National Biodiversity Institute to
develop,
manage,
co-ordinate,
promote
and
provide
assistance
on
biodiversity; to provide for the development an

----------------------------

[2026-03-16 14:17:47] INFO: Fetched (200) <GET https://pmg.org.za/bill/1228/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1228/> (referer: https://www.google.com/)

Bill ID: 1228
Title: Taxation Laws Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240801Draft_Taxation_Laws_Amendment_Bill.pdf

----- PDF TEXT PREVIEW -----

DRAFT


TAXATION LAWS AMENDMENT BILL

DRAFT


2

GENERAL EXPLANATORY NOTE:
[ ]
Words in bold type in square brackets indicate omissions from existing enactments.
_______ Words underlined with a solid line indicate insertions in existing enactments.



BILL
To amend the Income Tax Act, 1962, so as to amend certain definitions; to amend certain
provisions; to make new provision; to amend certain Schedules; to amend the Customs
and Excise Act, 1964, so as to make provision for continuations; to amend certain
Schedules; to amend the Value-Added Tax Act, 1991, so as to amend certain provisions; to
amend certain Schedules; and to make provision for continuations; to amend the
Securities Transfer Tax Act, 2007, to amend certain provisions; to amend the Mineral and
Petroleum Resources Royalty Act, 2008, so as to amend a provision; to amend the
Employment Tax Incentive Act, 2013, so as to amend certain provisions; to amend the
Taxation Laws Amendment Act, 2013, so as to a

----------------------------

[2026-03-16 14:18:04] INFO: Fetched (200) <GET https://pmg.org.za/bill/1229/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1229/> (referer: https://www.google.com/)

Bill ID: 1229
Title: Aeronautical and Maritime Search and Rescue Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240906aeronauticalmaritimesearchrescuebill-2-2.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 6 September 2024
No. 51171    89
REPUBLIC OF SOUTH AFRICA






AERONAUTICAL AND MARITIME SEARCH AND RESCUE BILL




_____________

(As introduced in the National Assembly (proposed section 76); explanatory summary of Bill
published in Government Gazette No. of )
(The English Text is the official text of the Bill)
______________



(MINISTER OF TRANSPORT)




(B – 2024)

This gazette is also available free online at www.gpwonline.co.za
90    No. 51171
GOVERNMENT GAZETTE, 6 September 2024
BILL
To provide for the establishment of the South African Search and Rescue
Organization; to provide for the composition, membership, powers, functions
of SASARO; to provide for the powers, functions, and appointment of members
to the Executive Committee of SASARO; to provide for the powers and
functions of the Management Committee; to provide for a National SAR Plan;
to provide for the

----------------------------

[2026-03-16 14:18:12] INFO: Fetched (200) <GET https://pmg.org.za/bill/1230/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1230/> (referer: https://www.google.com/)

Bill ID: 1230
Title: One-Stop Border Post Bill
Bill Number: (B12-2024)
PDF URL: https://pmg.org.za/files/parl-bills-B12B-2024-ag_B12B-2024-ag_1.pdf

----- PDF TEXT PREVIEW -----

JOBNAME: 2011 Western Cape Bi PAGE: 1 SESS: 35 OUTPUT: Wed Oct 22 14:48:30 2025 SUM: 09422924
/first/parliament−ag/parliament−bills−2025/parl−bills−B12B−2024−ag/B12B−2024−ag
REPUBLIC OF SOUTH AFRICA
ONE-STOP BORDER POST BILL
(As amended by the Portfolio Committee on Home Affairs)
(The English text is the offıcial text of the Bill)
(MINISTER OF HOME AFFAIRS)
[B 12B—2024]
ISBN 978-1-4850-xxxx-x
No. of copies printed ....................................... 150

JOBNAME: 2011 Western Cape Bi PAGE: 2 SESS: 35 OUTPUT: Wed Oct 22 14:48:30 2025 SUM: 473DB40F
/first/parliament−ag/parliament−bills−2025/parl−bills−B12B−2024−ag/B12B−2024−ag
BILL
To regulate the establishment of one-stop border posts through international
agreements; to provide for the establishment of common control zones in the
territory of an adjoining state; to provide for one-stop border processing
arrangements; to authorise the application of the laws of the Republic and the
adjoining state in the one-stop border post; and to

----------------------------

[2026-03-16 14:18:18] INFO: Fetched (200) <GET https://pmg.org.za/bill/1231/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1231/> (referer: https://www.google.com/)

Bill ID: 1231
Title: Tax Administration Laws Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/1/240801Draft_Tax_Administration_Laws_Amendment_Bill.pdf

----- PDF TEXT PREVIEW -----

DRAFT
REPUBLIC OF SOUTH AFRICA



TAX ADMINISTRATION LAWS AMENDMENT BILL, 2024

______________________

(As introduced in the National Assembly (proposed section 75); explanatory
summary of Bill published in Government Gazette No. of ) (The English text
is the official text of the Bill)
______________________




(MINISTER OF FINANCE)






[B - 2024]

2

GENERAL EXPLANATORY NOTE:
[ ]
Words in bold type in square brackets indicate omissions from
existing enactments.
___________
Words underlined with a solid line indicate insertions in existing
enactments.
___________________________________________________________________

BILL

To—
• amend the Income Tax Act, 1962, so as to correct an in incorrect cross-
reference; to amend the definition of “provisional taxpayer” in order to effect
a consequential amendment; effect a consequential amendment and remove
an obsolete cross reference; and to correct an in incorrect cross-reference;
• amend the Cust

----------------------------

[2026-03-16 14:18:26] INFO: Fetched (200) <GET https://pmg.org.za/bill/1232/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1232/> (referer: https://www.google.com/)

Bill ID: 1232
Title: Rates and Monetary Amounts and Amendment of Revenue Laws Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240221Draft_Rates_Bill.pdf

----- PDF TEXT PREVIEW -----

DRAFT
REPUBLIC OF SOUTH AFRICA
__________


DRAFT RATES AND MONETARY
AMOUNTS BILL





____________

(As introduced in the National Assembly (proposed section 77))
(The English text is the official text of the Bill)

______________




(MINISTER OF FINANCE)








21 February 2024






DB xx - 2024

2

DRAFT





GENERAL EXPLANATORY NOTE:

[
] Words in bold type in square brackets indicate omissions from existing
enactments.
________
Words underlined with a solid line indicate insertions in existing enactments.









BILL


To amend the Customs and Excise Act, 1964, so as to amend rates of duty in Schedule 1
to that Act; to amend the Carbon Tax Act, 2019, so as to amend rates; and to provide for
matters connected therewith.



E IT ENACTED by the Parliament of the Republic of South Africa, as follows:—


Amendment of Schedule 1 to Act 91 of 1964, as amended by section 19 of Act 95 of 1965,
section 15 of Act

----------------------------

[2026-03-16 14:18:34] INFO: Fetched (200) <GET https://pmg.org.za/bill/1233/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1233/> (referer: https://www.google.com/)

Bill ID: 1233
Title: Aeronautical and Maritime Search and Rescue Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240920aeronauticmarinesearchrescuebill-2-2.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za
92    No. 51271
GOVERNMENT GAZETTE, 20 September 2024

REPUBLIC OF SOUTH AFRICA






AERONAUTICAL AND MARITIME SEARCH AND RESCUE BILL




_____________

(As introduced in the National Assembly (proposed section 76); explanatory summary of Bill
published in Government Gazette No. of )
(The English Text is the official text of the Bill)
______________



(MINISTER OF TRANSPORT)




(B – 2024)

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 20 September 2024
No. 51271    93
BILL
To provide for the establishment of the South African Search and Rescue
Organization; to provide for the composition, membership, powers, functions
of SASARO; to provide for the powers, functions, and appointment of members
to the Executive Committee of SASARO; to provide for the powers and
functions of the Management Committee; to provide for a National SAR Plan;
to provide for

----------------------------

[2026-03-16 14:18:42] INFO: Fetched (200) <GET https://pmg.org.za/bill/1234/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1234/> (referer: https://www.google.com/)

Bill ID: 1234
Title: South African National Petroleum Company Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/240903SANPC_FINAL_BILL.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA


DRAFT SOUTH AFRICAN NATIONAL PETROLEUM COMPANY BILL, 2023


___________________

(As introduced in the National Assembly (proposed section 75); explanatory
summary of Bill published in Government Gazette No. of) (The English text is the
official text of the Bill)
---------------------------------


(MINISTER OF MINERAL RESOURCES AND ENERGY)




[B — 2023]

BILL

To provide for the establishment of the South African National Petroleum
Company; to provide for the objects and functions of the company; to provide
for the constitution of its board and the management thereof; to provide for its
finances; to provide for its chief executive officer and staff; to provide for
transitional arrangements for transferring human resources and assets from the
South African Gas Development Company (i Gas), Strategic Fuel Fund (SFF) and
Petroleum Oil and Gas Corporation of South Africa (Petro SA) to the South
African National Petroleum Company and t

----------------------------

[2026-03-16 14:18:51] INFO: Fetched (200) <GET https://pmg.org.za/bill/1235/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1235/> (referer: https://www.google.com/)

Bill ID: 1235
Title: Mine Health and Safety Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/MHS_Amendment_Bill_2022_PDF.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA



MINE HEALTH AND SAFETY AMENDMENT BILL


___________________

(As introduced in the National Assembly (proposed section 75); explanatory
summary of Bill published in Government Gazette No. of ) (The English
text is the official text of the Bill)
___________________





(MINISTER OF MINERAL AND PETROLEUM RESOURCES)






[B —2024]

2

010623lt
GENERAL EXPLANATORY NOTE:
[ ]
Words in bold type in square brackets indicate omissions from
existing enactments.
___________
Words underlined with a solid line indicate insertions in existing
enactments.
___________________________________________________________________
BILL

To amend the Mine Health and Safety Act, 1996, so as to streamline
administrative processes and substitute obsolete provisions; to strengthen
managerial responsibility and accountability; to provide for the further
composition of the Council; provide for the repeal of the establishment of the
Mining Qualif

----------------------------

[2026-03-16 14:19:02] INFO: Fetched (200) <GET https://pmg.org.za/bill/1236/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1236/> (referer: https://www.google.com/)

Bill ID: 1236
Title: Petroleum Products Draft Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/Draft_Petroleum_Products_Bill_2024..pdf
Page 2 needs OCR...
Page 3 needs OCR...
Page 4 needs OCR...
Page 5 needs OCR...
Page 6 needs OCR...
Page 7 needs OCR...
Page 8 needs OCR...
Page 9 needs OCR...
Page 10 needs OCR...
Page 11 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Page 14 needs OCR...
Page 15 needs OCR...
Page 16 needs OCR...
Page 17 needs OCR...
Page 18 needs OCR...
Page 19 needs OCR...
Page 20 needs OCR...
Page 21 needs OCR...
Page 22 needs OCR...
Page 23 needs OCR...
Page 24 needs OCR...
Page 25 needs OCR...
Page 26 needs OCR...
Page 27 needs OCR...
Page 28 needs OCR...
Page 29 needs OCR...
Page 30 needs OCR...
Page 31 needs OCR...
Page 32 needs OCR...
Page 33 needs OCR...
Page 34 needs OCR...
Page 35 needs OCR...
Page 36 needs OCR...
Page 37 needs OCR...
Page 38 needs OCR...
Page 39 needs OCR...
Page 40 needs OCR...
Page 41 needs OCR...
Page 42 needs OCR...
Page 43 needs OCR...
Page 44 needs OCR...
Page 45 needs OCR...
Page 46 needs OCR...
Page 47 needs OCR...
Page 48 needs OCR...
Page 49 needs OCR...
Page 50 needs OCR...
Page 51 needs OCR...
Page 52 needs OCR...
Page 53 needs OCR...
Page 54 needs OCR...
Page 55 needs OCR...
Page 56 needs OCR...
Page 57 needs OCR...
Page 58 needs OCR...

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 21 Oktober 2024
No. 51418    3
Government Notices • Goewermentskennisgewings
DEPARTMENT OF MINERAL RESOURCES AND ENERGY
NO. 5445
21 October 2024

4 No. 51418 GOVERNMENT GAZETTE, 21 OCTOBER 2024
REPUBLIC OF SOUTH AFRICA
PETROLEUM PRODUCTS BILL, 2024
(As introduced in the National Assembly (proposed section 76); explanatory summary
of Bill published in Government Gazette No. 51418 of 21% of October 2024 )
(The English text is the official text of the Bill)
(MINISTER OF MINERAL AND PETROLEUM RESOURCES)
[B - 2024]
This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 21 OKTOBER 2024 No. 51418 5
BILL
To provide for the efficient, cost effective, broadly representative and
competitive manufacturing, wholesaling and retailing of petroleum products in
South Africa through the control and management of the petroleum products
industry; to provide for the Controller, Regional Controlle

----------------------------

[2026-03-16 14:22:20] INFO: Fetched (200) <GET https://pmg.org.za/bill/1237/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1237/> (referer: https://www.google.com/)

Bill ID: 1237
Title: Adjustments Appropriation Bill
Bill Number: (B14-2024)
PDF URL: https://pmg.org.za/files/51832-adjustmentsappropriationact49of2024_1.pdf
Page 8 needs OCR...
Page 9 needs OCR...
Page 10 needs OCR...
Page 11 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Page 14 needs OCR...
Page 15 needs OCR...
Page 16 needs OCR...
Page 17 needs OCR...
Page 18 needs OCR...
Page 19 needs OCR...
Page 20 needs OCR...
Page 21 needs OCR...
Page 22 needs OCR...
Page 23 needs OCR...
Page 24 needs OCR...
Page 25 needs OCR...
Page 26 needs OCR...
Page 27 needs OCR...
Page 28 needs OCR...
Page 29 needs OCR...
Page 30 needs OCR...
Page 31 needs OCR...
Page 32 needs OCR...
Page 33 needs OCR...
Page 34 needs OCR...
Page 35 needs OCR...
Page 36 needs OCR...
Page 37 needs OCR...

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 714
24 December 2024
No. 51832
Cape Town
Kaapstad
No. 5742
No. 5742
24 December 2024
24 Desember 2024
Go itsisiwe gore Moporesidente o
dumetse Molao o o latelang, o o
phasaladiwang fano go itsisiwe botlhe:—
The Presidency
MOPORESIDENTE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act
No.49
of
2024:
Adjustments
Appropriation Act, Act 2024
No. 49 ya 2024: Molao wa Dipaakanyo tsa
Ditekanyetso, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 8 3 2
ISSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51832
GOVERNMENT GAZETTE, 24 December 2024
Act No.49 of 2024
Adjustments Appropriation Act, Act 2024
ACT
To effect adjustments to the appropriation of money from the National Revenue
Fund for the requirements of the State in respect of the 2024/25 ﬁnancial year; and
to pr

----------------------------

[2026-03-16 14:24:37] INFO: Fetched (200) <GET https://pmg.org.za/bill/1238/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1238/> (referer: https://www.google.com/)

Bill ID: 1238
Title: Rates and Monetary Amounts Amendment Bill
Bill Number: (B15-2024)
PDF URL: https://pmg.org.za/files/51829_24-12_Rates_and_Monetary_Amounts_Amendment_Act45_2024.pdf

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 714
24 December 2024
No. 51829
Cape Town
Kaapstad
No. 5739
No. 5739
24 December 2024
24 Desember 2024
Hierby word bekend gemaak dat die
President sy goedkeuring geheg het
aan die onderstaande Wet wat hierby ter
algemene inligting gepubliseer word:—
The Presidency
DIE PRESIDENSIE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No.45 of 2024: Rates and Monetary
Amounts Amendment, Act 2024
No. 45 van 2024: Wysigingswet op skale en
monetere bedrae, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 8 2 9
ISSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51829
GOVERNMENT GAZETTE, 24 December 2024
Act No.45 of 2024
Rates and Monetary Amounts Amendment, Act 2024
GENERAL EXPLANATORY NOTE:
[
]
Words in bold type in square brackets indicate omissions from
existing enactments

----------------------------

[2026-03-16 14:24:46] INFO: Fetched (200) <GET https://pmg.org.za/bill/1239/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1239/> (referer: https://www.google.com/)

Bill ID: 1239
Title: Taxation Laws Amendment Bill
Bill Number: (B16-2024)
PDF URL: https://pmg.org.za/files/51826_24-12_Taxation_Laws_Amendment_Act42_2024.pdf

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 714
24 December 2024
No. 51826
Cape Town
Kaapstad
No. 5736
No. 5736
24 December 2024
24 Desember 2024
Hierby word bekend gemaak dat die
President sy goedkeuring geheg het
aan die onderstaande Wet wat hierby ter
algemene inligting gepubliseer word:—
The Presidency
DIE PRESIDENSIE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No.42 of 2024: Taxation Laws
Amendment, Act 2024
Wet No. 42 van 2024: Wysigingswet op
belastingwette, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 8 2 6
ISSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51826
GOVERNMENT GAZETTE, 24 December 2024
Act No.42 of 2024
Taxation Laws Amendment, Act 2024
GENERAL EXPLANATORY NOTE:
[
]
Words in bold type in square brackets indicate omissions from
existing enactments.
Words underlined with a solid

----------------------------

[2026-03-16 14:25:09] INFO: Fetched (200) <GET https://pmg.org.za/bill/1240/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1240/> (referer: https://www.google.com/)

Bill ID: 1240
Title: Revenue Laws Amendment Bill
Bill Number: (B18-2024)
PDF URL: https://pmg.org.za/files/51828-revenuelawssecondamendmentact44of2024.pdf

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 714
24 December 2024
No. 51828
Cape Town
Kaapstad
No. 5738
No. 5738
24 December 2024
24 Desember 2024
Hierby word bekend gemaak dat die
President sy goedkeuring geheg het
aan die onderstaande Wet wat hierby ter
algemene inligting gepubliseer word:—
The Presidency
DIE PRESIDENSIE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No.44 of 2024: The Revenue Laws
Second Amendment, Act 2024
No. 44 van 2024:Tweede Wysigingswet op
inkomstewette, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 8 2 8
ISSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51828
GOVERNMENT GAZETTE, 24 December 2024
Act No.44 of 2024
The Revenue Laws Second Amendment, Act 2024
GENERAL EXPLANATORY NOTE:
[
]
Words in bold type in square brackets indicate omissions from
existing enactments.
Words und

----------------------------

[2026-03-16 14:25:21] INFO: Fetched (200) <GET https://pmg.org.za/bill/1241/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1241/> (referer: https://www.google.com/)

Bill ID: 1241
Title: Special Appropriation Bill
Bill Number: (B19-2024)
PDF URL: https://pmg.org.za/files/51833_24-12_Special_Appropriation_Act50_2024_1.pdf
Page 4 needs OCR...
Page 5 needs OCR...

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 714
24 December 2024
No. 51833
Cape Town
Kaapstad
No. 5743
No. 5743
24 December 2024
24 Desember 2024
Go itsisiwe gore Moporesidente o
dumetse Molao o o latelang, o o
phasaladiwang fano go itsisiwe botlhe:—
The Presidency
MOPORESIDENTE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act
No.
50

of
2024:
Special
Appropriation Act, Act 2024
No. 50 ya 2024: Molao wa Tekanyetso e e
kgethegileng, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 8 3 3
ISSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51833
GOVERNMENT GAZETTE, 24 December 2024
Act No.50 of 2024
Special Appropriation Act, Act 2024
ACT
To appropriate an additional amount of money for the requirements of the State
for the 2024/25 ﬁnancial year; and to provide for matters connected therewith.
B
E IT ENACTE

----------------------------

[2026-03-16 14:25:36] INFO: Fetched (200) <GET https://pmg.org.za/bill/1242/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1242/> (referer: https://www.google.com/)

Bill ID: 1242
Title: Global Minimum Tax Bill
Bill Number: (B20-2024)
PDF URL: https://pmg.org.za/files/51830-globalminimumtaxact46of2024.pdf

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 714
24 December 2024
No. 51830
Cape Town
Kaapstad
No. 5740
No. 5740
24 December 2024
24 Desember 2024
Hierby word bekend gemaak dat die
President sy goedkeuring geheg het
aan die onderstaande Wet wat hierby ter
algemene inligting gepubliseer word:—
The Presidency
DIE PRESIDENSIE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No.46 of 2024: Global Minimum Tax
Act, Act 2024
No. 46 van 2024: Wet op globale minimum
belasting, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 8 3 0
ISSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51830
GOVERNMENT GAZETTE, 24 December 2024
Act No.46 of 2024
Global Minimum Tax Act, Act 2024
ACT
To provide for the introduction of the Global Anti-Base Erosion (Glo BE) Rules in
South Africa; to provide for the imposition of Top-up Tax; an

----------------------------

[2026-03-16 14:25:44] INFO: Fetched (200) <GET https://pmg.org.za/bill/1243/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1243/> (referer: https://www.google.com/)

Bill ID: 1243
Title: Tax Administration Laws Amendment Bill
Bill Number: (B17-2024)
PDF URL: https://pmg.org.za/files/51827_24-12_Tax_Administration_Laws_Amendment_Act43_2024.pdf

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 714
24 December 2024
No. 51827
Cape Town
Kaapstad
No. 5737
No. 5737
24 December 2024
24 Desember 2024
Hierby word bekend gemaak dat die
President sy goedkeuring geheg het
aan die onderstaande Wet wat hierby ter
algemene inligting gepubliseer wordi:—
The Presidency
DIE PRESIDENSIE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No.43 of 2024: Tax Administration
Laws Amendment, Act 2024
No.
43
van
2024:
Wysigingswet
op
Belastingadministrasiewette, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 8 2 7
ISSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51827
GOVERNMENT GAZETTE, 24 December 2024
Act No.43 of 2024
Tax Administration Laws Amendment, Act 2024
GENERAL EXPLANATORY NOTE:
[
]
Words in bold type in square brackets indicate omissions from
existing enactme

----------------------------

[2026-03-16 14:25:55] INFO: Fetched (200) <GET https://pmg.org.za/bill/1244/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1244/> (referer: https://www.google.com/)

Bill ID: 1244
Title: Division of Revenue Amendment Bill
Bill Number: (B13-2024)
PDF URL: https://pmg.org.za/files/51831-divisionrevenueamendmentact48of2024.pdf
Page 12 needs OCR...
Page 22 needs OCR...
Page 26 needs OCR...

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 714
24 December 2024
No. 51831
Cape Town
Kaapstad
No. 5741
No. 5741
24 December 2024
24 Desember 2024
Esi
sisaziso
sokuba
u Mongameli
uwamkele
lo
mthetho
ulandelayo
nonikezelwayo kuluntu jikelele kolu
xwebhu:—
The Presidency
I-OFISI KAMONGAMELI
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No. 48 of 2024: Division of Revenue
Amendment, Act 2024
Ino
48
ka
2024:
Umthetho-sihlomelo
wokwahlulwa-hlulwa kwengeniso, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 8 3 1
ISSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51831
GOVERNMENT GAZETTE, 24 December 2024
Act No.48 of 2024
Division of Revenue Amendment, Act 2024
ACT
To amend the Division of Revenue Act, 2024, in accordance with the Money Bills
and Related Matters Act, 2009; and to provide for matters c

----------------------------

[2026-03-16 14:26:24] INFO: Fetched (200) <GET https://pmg.org.za/bill/1245/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1245/> (referer: https://www.google.com/)

Bill ID: 1245
Title: Global Minimum Tax Administration Bill
Bill Number: (B21-2024)
PDF URL: https://pmg.org.za/files/globalminimumtaxadministrationact47of2024.pdf

----- PDF TEXT PREVIEW -----

cure
the
is
Prevention
0800-0123-22
HELPLINE:
AIDS
REPUBLIC OF SOUTH AFRICA
Government Gazette
Vol. 715
9 January 2025
No. 51884
Cape Town
Kaapstad
No. 5742
No. 5742
9 January 2025
9 Januarie 2025
Hierby word bekend gemaak dat die
President sy goedkeuring geheg het
aan die onderstaande Wet wat hierby ter
algemene inligting gepubliseer word:—
The Presidency
DIE PRESIDENSIE
It is hereby notified that the President
has assented to the following Act,
which is hereby published for general
information:—
Act No. 47 of 2024: Global Minimum Tax
Administration, Act 2024
No. 47 van 2024: Wet op Globale Minimum
Belasting Administrasie, 2024
9
7 7 1 6 8 2 5 8 4 0 0 3
5 1 8 8 4
ISSN 1682-5845

This gazette is also available free online at www.gpwonline.co.za
2    No. 51884
GOVERNMENT GAZETTE, 9 January 2025
Act No. 47 of 2024
Global Minimum Tax Administration, Act 2024
ACT
To provide for the administration of the Global Minimum Tax Act; and to provide
for matters connected therewith.

----------------------------

[2026-03-16 14:26:30] INFO: Fetched (200) <GET https://pmg.org.za/bill/1246/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1246/> (referer: https://www.google.com/)

Bill ID: 1246
Title: Constitution Twenty-First Amendment Bill (PMB)
Bill Number: (B22-2024)
PDF URL: https://pmg.org.za/files/B22-2024_Constitution_Twenty-First.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA
CONSTITUTION TWENTY-FIRST
AMENDMENT BILL
(As introduced in the National Assembly (proposed section 74(3)(a); explanatory summary
of Bill and prior notice of its introduction published in Government Gazette No. 50528
of 19 April 2024)
(The English text is the offıcial text of the Bill)
(ADV G BREYTENBACH, MP)
[B 22—2024]
ISBN 978-1-4850-1007-4
No. of copies printed .........................................150

GENERAL EXPLANATORY NOTE:
[
]
Words in bold type in square brackets indicate omissions from
existing enactments.
Words underlined with a solid line indicate insertions in
existing enactments.
BILL
To amend the Constitution of the Republic of South Africa, 1996, so as to establish
the Anti-Corruption Commission as an institution supporting and strengthening
constitutional democracy in the Republic; and to provide for matters connected
therewith.
B
E IT ENACTED by the Parliament of the Republic of South Africa, as follows:—
Amendment of section 179 of Consti

----------------------------

[2026-03-16 14:26:38] INFO: Fetched (200) <GET https://pmg.org.za/bill/1247/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1247/> (referer: https://www.google.com/)

Bill ID: 1247
Title: Special Pensions Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/Draft_Special_Pensions_Amendment_Bill_-_public_comment_1-11-2024.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA





DRAFT

SPECIAL PENSIONS AMENDMENT BILL

________________

(As introduced in the National Assembly (proposed section 75); explanatory
summary of Bill and prior notice of its introduction published in Government
Gazette…)
(The English text is the official text of the Bill)
_________________





(MINISTER OF FINANCE)











[B —2024]

2

GENERAL EXPLANATORY NOTE:

[ ]
Words in bold type in square brackets indicate omissions from
the existing enactments.
___________
Words underlined with solid line indicate insertions in existing
enactments.
___________________________________________________________________
BILL

To amend the Special Pensions Act, 1996, so as to provide for the retention of
benefits that have been determined before the lapsing of certain provisions; to
allow persons who qualify for more than one benefit to be granted the most
advantageous benefit; to provide the surviving spouse or benefi

----------------------------

[2026-03-16 14:26:45] INFO: Fetched (200) <GET https://pmg.org.za/bill/1248/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1248/> (referer: https://www.google.com/)

Bill ID: 1248
Title: Local Government: Municipal Structures Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/241108localgovmunicipalstructuresamenddraftbill-2-2.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 8 November 2024
No. 51526    67
REPUBLIC OF SOUTH AFRICA
LOCAL GOVERNMENT: MUNICIPAL
STRUCTURES AMENDMENT BILL
(As introduced in the National Assembly (proposed section 75); The Bill and prior
notice of its introduction published in Government Gazette No. 51526 of
8 November 2024)
(The English text is the official text of the Bill)
(MR. G MICHALAKIS, MP)
[B —2024]
ISBN
No. of copies printed ......................

This gazette is also available free online at www.gpwonline.co.za
68    No. 51526
GOVERNMENT GAZETTE, 8 November 2024
GENERAL EXPLANATORY NOTE:
[ ]
Words in bold type in square brackets indicate omissions from existing
enactments.
Words underlined with a solid line indicate insertions in existing enactments.
 BILL
To amend the Local Government: Municipal Structures Act, 1998, so as to limit the
frequency in terms of which a motion to remove a speaker from office may be tabled

----------------------------

[2026-03-16 14:26:51] INFO: Fetched (200) <GET https://pmg.org.za/bill/1249/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1249/> (referer: https://www.google.com/)

Bill ID: 1249
Title: Intergovernmental Relations Framework Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/Intergovernmental_Relations_Framework_Amendment_Bill__Draft.pdf
Page 1 needs OCR...
Page 2 needs OCR...
Page 3 needs OCR...
Page 4 needs OCR...
Page 5 needs OCR...
Page 6 needs OCR...
Page 7 needs OCR...
Page 8 needs OCR...
Page 9 needs OCR...
Page 10 needs OCR...
Page 11 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Page 14 needs OCR...
Page 15 needs OCR...
Page 16 needs OCR...
Page 17 needs OCR...
Page 18 needs OCR...
Page 19 needs OCR...
Page 20 needs OCR...
Page 21 needs OCR...
Page 22 needs OCR...
Page 23 needs OCR...
Page 24 needs OCR...
Page 25 needs OCR...
Page 26 needs OCR...
Page 27 needs OCR...
Page 28 needs OCR...
Page 29 needs OCR...

----- PDF TEXT PREVIEW -----

STAATSKOERANT, 29 NOVEMBER 2024 No. 51657 65
REPUBLIC OF SOUTH AFRICA
INTERGOVERNMENTAL RELATIONS FRAMEWORK AMENDMENT BILL
(As introduced in the National Assembly (proposed section 76); explanatory
summary of Bill and prior notice of its introduction published in Government Gazette
No. ----of----) (The English text is the official text of the Bill)
(MINISTER OF COOPERATIVE GOVERNANCE AND TRADITIONAL AFFAIRS)
[B — 2024]
This gazette is also available free online at www.gpwonline.co.za

66 No. 51657 GOVERNMENT GAZETTE, 29 NOVEMBER 2024
050224nb
GENERAL EXPLANATORY NOTE:
[ ] Words in bold type in square brackets indicate omissions from
existing enactments.
Words underlined with a solid line indicate insertions in existing
enactments.
BILL
To amend the Intergovernmental Relations Framework Act, 2005, so as to insert
certain definitions; to establish new intergovernmental structures and increase
the composition of the existing intergovernmental structures; to prescribe the
minimum number of

----------------------------

[2026-03-16 14:28:20] INFO: Fetched (200) <GET https://pmg.org.za/bill/1250/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1250/> (referer: https://www.google.com/)

Bill ID: 1250
Title: Traditional and Khoi-San Leadership Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/Traditional_and_Khoi-San_Leadership_Bill__Draft_cut.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 29 November 2024
No. 51657    165
REPUBLIC OF SOUTH AFRICA






TRADITIONAL AND KHOI-SAN
LEADERSHIP BILL









(As introduced in the National Assembly as a section 76 Bill;
Bill published in Government Gazette No. of )
(The English text is the official text of the Bill)






(MINISTER OF COOPERATIVE GOVERNANCE AND TRADITIONAL AFFAIRS)

























[B —2024]
ISBN

This gazette is also available free online at www.gpwonline.co.za
166    No. 51657
GOVERNMENT GAZETTE, 29 November 2024
BILL
To provide for the recognition of traditional and Khoi-San communities,
leadership positions and for the withdrawal of such recognition; to provide for the
functions and roles of traditional and Khoi-San leaders; to provide for the
recognition, establishment, functions, roles and administration of kingship or
queenship councils, principal traditi

----------------------------

[2026-03-16 14:28:50] INFO: Fetched (200) <GET https://pmg.org.za/bill/1251/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1251/> (referer: https://www.google.com/)

Bill ID: 1251
Title: Draft Revenue Laws Amendment Bill 2025
Bill Number: (X-2025)
PDF URL: https://pmg.org.za/files/Draft_Revenue_Laws_Amendment_Bill_2025.pdf

----- PDF TEXT PREVIEW -----

DRAFT
REVENUE LAWS AMENDMENT BILL





10 December 2024

















[Bxx–2025]

DRAFT


2
GENERAL EXPLANATORY NOTE:
[
]
Words in bold type in square brackets indicate omissions from existing
enactments.
_______
Words underlined with a solid line indicate insertions in existing
enactments.


BILL

To amend the Income Tax Act, 1962, so as to amend certain definitions; to
amend certain provisions; and to provide for matters connected therewith.

BE IT ENACTED by the Parliament of the Republic of South Africa, as follows:—

Amendment of section 1 of Act 58 of 1962, as amended by section 3 of Act 90 of
1962, section 1 of Act 6 of 1963, section 4 of Act 72 of 1963, section 4 of Act 90
of 1964, section 5 of Act 88 of 1965, section 5 of Act 55 of 1966, section 5 of Act
76 of 1968, section 6 of Act 89 of 1969, section 6 of Act 52 of 1970, section 4 of
Act 88 of 1971, section 4 of Act 90 of 1972, section 4 of Act 65 of 1973, section 4
of Ac

----------------------------

[2026-03-16 14:28:56] INFO: Fetched (200) <GET https://pmg.org.za/bill/1252/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1252/> (referer: https://www.google.com/)

Bill ID: 1252
Title: Judicial Matters Amendment Bill
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/Judicial_Matters_Amendment_Bill__Publication_of_Explanatory_Summary_of_the_Bill__Eng_Afr.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA



JUDICIAL MATTERS AMENDMENT BILL, 2024



_______________

(As introduced in the National Assembly (proposed section 75); explanatory
summary of Bill published in Government Gazette No. of 2024)
(The English text is the offıcial text of the Bill)
_______________




(MINISTER OF JUSTICE AND CONSTITUTIONAL DEVELOPMENT)










[2024]

2

GENERAL EXPLANATORY NOTE:

[ ]
Words in bold type in square brackets indicate omissions from
existing enactments
___________
Words underlined with a solid line indicate insertions in existing
enactments
___________________________________________________________________

BILL

To amend the—
•
Judicial Service Commission Act, 1994, so as to further regulate the
composition of the Judicial Conduct Committee;
•
Promotion of Access to Information Act, 2000, so as to—
•
make provision for the manual to also contain the website link to the
latest notice regarding the records held

----------------------------

[2026-03-16 14:29:03] INFO: Fetched (200) <GET https://pmg.org.za/bill/1253/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1253/> (referer: https://www.google.com/)

Bill ID: 1253
Title: South African Geographical Names Council Amendment Bill
Bill Number: (X-2025)
PDF URL: https://pmg.org.za/files/South_African_Geographical_Name_Council_Amendment_Act.pdf

----- PDF TEXT PREVIEW -----

REPUBLIC OF SOUTH AFRICA




SOUTH AFRICAN GEOGRAPHICAL NAMES COUNCIL AMENDMENT BILL


--------------------------------
(As introduced in the National Assembly (proposed section 75); explanatory
summary of Bill and prior notice of its introduction published in Government Gazette
No. of ) (The English text is the official text of the Bill)
---------------------------------




(MINISTER OF SPORTS, ARTS AND CULTURE)





[B – 2023]

2

081122lt

GENERAL EXPLANATORY NOTE:
[ ]
Words in bold type in square brackets indicate omissions from the
existing enactment.

___________
Words underlined with a solid line indicate insertions in existing
enactment.


BILL

To amend the South African Geographical Names Council, Act, so as to insert
certain definitions; to provide for the establishment and functions of the
Provincial Geographical Names Committee; to provide anew for the term of
office of members of the South African Geographical Names Council; to


----------------------------

[2026-03-16 14:29:11] INFO: Fetched (200) <GET https://pmg.org.za/bill/1254/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1254/> (referer: https://www.google.com/)

Bill ID: 1254
Title: Local Government: Municipal Structures Amendment Bill
Bill Number: (X-2025)
PDF URL: https://pmg.org.za/files/Local_Government__Municipal_Structures_Amendment_Bill__Draft__Comments_invited.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za
STAATSKOERANT, 24 Januarie 2025
No. 51950    75
REPUBLIC OF SOUTH AFRICA
LOCAL GOVERNMENT: MUNICIPAL
STRUCTURES AMENDMENT BILL
(As introduced in the National Assembly (proposed section 75); Bill and prior notice of its
introduction published in Government Gazette No. XXXXXXX);
(The English text is the official text of the Bill)
(Mr G Michalakis, MP)
[B x —2025]
ISBN
No. of copies printed ....................................................................

This gazette is also available free online at www.gpwonline.co.za
76    No. 51950
GOVERNMENT GAZETTE, 24 January 2025
GENERAL EXPLANATORY NOTE:
[
 ]
 Words in bold type in square brackets indicate omissions from
existing enactments.
Words underlined with a solid line indicate insertions in
existing enactments.
BILL
To amend the Local Government: Municipal Structures Act, 1998, so as to extend the time
period within which a local council must appoint

----------------------------

[2026-03-16 14:29:17] INFO: Fetched (200) <GET https://pmg.org.za/bill/1255/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (200) <GET https://pmg.org.za/bill/1255/> (referer: https://www.google.com/)

Bill ID: 1255
Title: Economic Regulation of Transport Amendment Bill 2024
Bill Number: (X-2024)
PDF URL: https://pmg.org.za/files/241206draft-economic-regulation-of-transport-amendment-bill.pdf

----- PDF TEXT PREVIEW -----

This gazette is also available free online at www.gpwonline.co.za
230    No. 51711
GOVERNMENT GAZETTE, 6 December 2024
REPUBLIC OF SOUTH AFRICA

-----------------



ECONOMIC REGULATION OF TRANSPORT AMENDMENT BILL



-----------------

(As introduced in the National Assembly (proposed section 75); Bill and prior notice of its
introduction published in Government Gazette No. of

)
(The English text is the official text of the Bill)

__________


(Portfolio Committee on Transport)

This gazette is also available free online at www.gpwonline.co.za

STAATSKOERANT, 6 Desember 2024
No. 51711    231
BILL

To amend the Economic Regulation of Transport Act, 2024, so as to correct erroneous
references in Schedule 1 to the Act; and to provide for matters connected therewith.
BE IT ENACTED by the Parliament of the Republic of South Africa, as follows: ―
Amendment of Schedule 1 to Act 6 of 2024
1.
Schedule 1 to the Economic Regulation of Transport Act, 2024 (Act No. 6

----------------------------

[2026-03-16 14:29:22] INFO: Fetched (404) <GET https://pmg.org.za/bill/1256/> (referer: https://www.google.com/)
INFO:scrapling:Fetched (404) <GET https://pmg.org.za/bill/1256/> (referer: https://www.google.com/)

IndexError: list index out of range

## Show data loaded

In [ ]:
rows = bill_table.scan().to_pandas()



# Get the largest bill_identifier
max_bill_id = rows['bill_identifier'].max()

print("Largest bill_identifier:", max_bill_id)

min_bill_id = rows['bill_identifier'].min()
print("Smallest bill_identifier:", min_bill_id)

min_row = rows.loc[rows['bill_identifier'] == rows['bill_identifier'].min()]
print(min_row)

## Store PDFs

In [ ]:
import requests
import re
from io import BytesIO

def sanitize_proceedings_filename(name: str) -> str:
    name = re.sub(r'[\\/*?:"<>|]', "", name)
    name = name.replace(" ", "_")
    return name

from io import BytesIO
import requests

def upload_bills_to_s3(bills, s3_client, bucket_name):

    uploaded = 0

    for bill in bills:
        try:

            pdf_url = bill["pdf_url"]
            bill_id = bill["bill_identifier"]

            filename = f"{bill_id}.pdf"
            s3_key = f"bills/{filename}"

            print(f"Uploading {filename}...")

            response = requests.get(pdf_url)

            if response.status_code != 200:
                print(f"Failed to download {pdf_url}")
                continue

            file_bytes = BytesIO(response.content)

            s3_client.upload_fileobj(
                file_bytes,
                bucket_name,
                s3_key
            )

            uploaded += 1

        except Exception as e:
            print(f"Upload failed for {bill['title']}: {e}")

    print(f"{uploaded} files uploaded to s3://{bucket_name}/bills/")

## Retreive bills from PMG

In [ ]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from pyiceberg.catalog import load_catalog
from pyiceberg.expressions import In
import httpx
import asyncio
import json


from scrapling.fetchers import StealthyFetcher
import requests
import pdfplumber
from pdf2image import convert_from_path
import pytesseract
import tempfile
import os
import re

def extract_pdf_text(url_or_path, is_url=True):
    """
    Extract PDF text using:
    - pdfplumber for initial extraction
    - OCR if text is empty or contains '(cid:'
    - fitz as fallback for normal pages
    """
    # Get PDF bytes
    if is_url:
        pdf_bytes = requests.get(url_or_path).content
    else:
        with open(url_or_path, "rb") as f:
            pdf_bytes = f.read()

    text_output = ""

    # First attempt: pdfplumber + OCR
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for i, page in enumerate(pdf.pages):


            page_text = page.extract_text()
            page_text_str = page_text if page_text else ""

            # Decide if OCR is needed
            if not page_text_str.strip() or '(cid:' in page_text_str:
                print(f"Page {i + 1} needs OCR...")

                images = convert_from_bytes(pdf_bytes, first_page=i+1, last_page=i+1, dpi=300)
                ocr_text = ""
                for img in images:
                    ocr_text += pytesseract.image_to_string(img) + "\n\n"

                page_text_str = ocr_text
            else:
                # fallback: use fitz for better normal text extraction
                doc = fitz.open(stream=pdf_bytes, filetype="pdf")
                fitz_page_text = doc[i].get_text()
                if fitz_page_text:
                    page_text_str = fitz_page_text

            # Clean spacing
            page_text_str = re.sub(r'\n+', '\n', page_text_str)                  # reduce multiple newlines
            page_text_str = re.sub(r' +', ' ', page_text_str)                    # reduce multiple spaces
            page_text_str = re.sub(r'([a-z])([A-Z])', r'\1 \2', page_text_str)  # fix missing spaces

            text_output += page_text_str.strip() + "\n\n"

    return text_output


warehouse_path = "/content/warehouse"
s3_uri = "https://15c46705015d147b9bbf2d532ce26495.r2.cloudflarestorage.com"
catalog = rest.RestCatalog(
    name="default",
    warehouse="15c46705015d147b9bbf2d532ce26495_standard-deviants-storage",
    uri="https://catalog.cloudflarestorage.com/15c46705015d147b9bbf2d532ce26495/standard-deviants-storage",
    token=userdata.get('CLOUDFLARE_API_KEY'),
)
if not catalog.namespace_exists("default"):
  catalog.create_namespace("default")

table_name = "default.bills"


bill_schema = pa.schema([
    ("bill_identifier", pa.int64()),
    ("title", pa.string()),
    ("bill_number", pa.int64()),
    ("year", pa.int32()),
    ("act_name", pa.string()),
    ("introduced_by", pa.string()),
    ("date_of_introduction", pa.string()),
    ("date_of_assent", pa.string()),
    ("effective_date", pa.string()),
    ("status_name", pa.string()),
    ("type_name", pa.string()),
    ("events_json", pa.string()),
    ("pdf_url", pa.string()),
    ("pdf_text", pa.string()),
])


if not catalog.table_exists(table_name):
    bill_table = catalog.create_table(table_name, schema=bill_schema)
else:
    bill_table = catalog.load_table(table_name)



start_bill_id = 1208
end_bill_id = 1335

bills = []

for bill_id in range(start_bill_id, end_bill_id + 1):

    api_url = f"https://api.pmg.org.za/bill/{bill_id}/"
    print(f"Fetching {api_url}")

    try:
        async with httpx.AsyncClient() as client:
            response = await client.get(api_url)
            response.raise_for_status()
            bill_data = response.json()


        title = bill_data.get("title")
        bill_number = bill_data.get("number")
        year = bill_data.get("year")
        act_name = bill_data.get("act_name")
        introduced_by = bill_data.get("introduced_by")
        date_of_introduction = bill_data.get("date_of_introduction")
        date_of_assent = bill_data.get("date_of_assent")
        effective_date = bill_data.get("effective_date")
        status_name = bill_data.get("status", {}).get("name")
        type_name = bill_data.get("type", {}).get("name")

        pdf_url = None
        versions = bill_data.get("versions", [])
        if versions:
            pdf_url = versions[0].get("file", {}).get("url")

        filename = f"bill_{bill_id}_text.txt"
        # if os.path.exists(filename):
        #   print(f"Reading saved text for Bill {bill_id} from {filename}")

        #   with open(filename, "r", encoding="utf-8") as f:
        #       pdf_text = f.read()
        # else:
        pdf_text = ""
        if pdf_url:
            try:
                pdf_text = extract_pdf_text(pdf_url)

                # Save it for future runs
                with open(filename, "w", encoding="utf-8") as f:
                    f.write(pdf_text)

            except Exception as e:
                print(f"Error extracting PDF text: {e}")

            events_json = json.dumps(bill_data.get("events", []))
            full_response_json = json.dumps(bill_data)

        bills.append({
            "bill_identifier": bill_id,
            "title": title,
            "bill_number": bill_number,
            "year": year,
            "act_name": act_name,
            "introduced_by": introduced_by,
            "date_of_introduction": date_of_introduction,
            "date_of_assent": date_of_assent,
            "effective_date": effective_date,
            "status_name": status_name,
            "type_name": type_name,
            "events_json": events_json,
            "pdf_url": pdf_url,
            "pdf_text": pdf_text,
        })

    except httpx.HTTPStatusError as e:
        print(f"HTTP error for Bill ID {bill_id}: {e}")
    except Exception as e:
        print(f"An unexpected error occurred for Bill ID {bill_id}: {e}")

if bills:
    df = pd.DataFrame(bills)
    arrow_table = pa.Table.from_pandas(df, schema=bill_schema, preserve_index=False)

    bill_table.append(arrow_table)
    print(f"{len(bills)} new bills inserted into Iceberg table '{table_name}'.")

    upload_bills_to_s3(bills, s3_client, bucket_name)


else:
    print("No new bills to insert.")

Fetching https://api.pmg.org.za/bill/1208/
Page 31 needs OCR...
Fetching https://api.pmg.org.za/bill/1209/
Fetching https://api.pmg.org.za/bill/1210/
Page 2 needs OCR...
Page 3 needs OCR...
Fetching https://api.pmg.org.za/bill/1211/
Page 96 needs OCR...
Page 106 needs OCR...
Page 110 needs OCR...
Fetching https://api.pmg.org.za/bill/1212/
Page 5 needs OCR...
Page 7 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Page 14 needs OCR...
Page 15 needs OCR...
Page 16 needs OCR...
Page 17 needs OCR...
Page 18 needs OCR...
Page 19 needs OCR...
Page 20 needs OCR...
Page 21 needs OCR...
Page 22 needs OCR...
Page 23 needs OCR...
Page 24 needs OCR...
Page 25 needs OCR...
Page 26 needs OCR...
Page 27 needs OCR...
Page 28 needs OCR...
Page 29 needs OCR...
Page 30 needs OCR...
Page 31 needs OCR...
Page 32 needs OCR...
Page 33 needs OCR...
Page 34 needs OCR...
Page 35 needs OCR...
Page 36 needs OCR...
Page 37 needs OCR...
Page 38 needs OCR...
Page 39 needs OCR...
Page 40 needs OCR...
Page 41 needs OCR...
Page 42 needs OCR...
Page 43 needs OCR...
Page 44 needs OCR...
Page 45 needs OCR...
Page 46 needs OCR...
Page 47 needs OCR...
Page 48 needs OCR...
Page 49 needs OCR...
Page 50 needs OCR...
Page 51 needs OCR...
Page 52 needs OCR...
Page 53 needs OCR...
Page 54 needs OCR...
Page 55 needs OCR...
Page 56 needs OCR...
Page 57 needs OCR...
Page 58 needs OCR...
Page 59 needs OCR...
Page 60 needs OCR...
Page 61 needs OCR...
Page 62 needs OCR...
Page 63 needs OCR...
Page 64 needs OCR...
Page 65 needs OCR...
Page 66 needs OCR...
Page 67 needs OCR...
Page 68 needs OCR...
Page 69 needs OCR...
Page 70 needs OCR...
Page 71 needs OCR...
Page 72 needs OCR...
Page 73 needs OCR...
Page 74 needs OCR...
Page 75 needs OCR...
Page 76 needs OCR...
Page 77 needs OCR...
Page 79 needs OCR...
Page 80 needs OCR...
Page 81 needs OCR...
Page 82 needs OCR...
Page 83 needs OCR...
Fetching https://api.pmg.org.za/bill/1213/
Page 7 needs OCR...
Fetching https://api.pmg.org.za/bill/1214/
Fetching https://api.pmg.org.za/bill/1215/
Fetching https://api.pmg.org.za/bill/1216/
Fetching https://api.pmg.org.za/bill/1217/
Fetching https://api.pmg.org.za/bill/1218/
Fetching https://api.pmg.org.za/bill/1219/
Page 6 needs OCR...
Page 7 needs OCR...
Fetching https://api.pmg.org.za/bill/1220/
Fetching https://api.pmg.org.za/bill/1221/
Fetching https://api.pmg.org.za/bill/1222/
Fetching https://api.pmg.org.za/bill/1223/
Fetching https://api.pmg.org.za/bill/1224/
Fetching https://api.pmg.org.za/bill/1225/
Fetching https://api.pmg.org.za/bill/1226/
Page 1 needs OCR...
Page 2 needs OCR...
Page 3 needs OCR...
Page 4 needs OCR...
Page 5 needs OCR...
Page 6 needs OCR...
Page 7 needs OCR...
Page 8 needs OCR...
Page 9 needs OCR...
Page 10 needs OCR...
Page 11 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Fetching https://api.pmg.org.za/bill/1227/
Fetching https://api.pmg.org.za/bill/1228/
Fetching https://api.pmg.org.za/bill/1229/
Fetching https://api.pmg.org.za/bill/1230/
Fetching https://api.pmg.org.za/bill/1231/
Fetching https://api.pmg.org.za/bill/1232/
Fetching https://api.pmg.org.za/bill/1233/
Fetching https://api.pmg.org.za/bill/1234/
Fetching https://api.pmg.org.za/bill/1235/
Fetching https://api.pmg.org.za/bill/1236/
Page 2 needs OCR...
Page 3 needs OCR...
Page 4 needs OCR...
Page 5 needs OCR...
Page 6 needs OCR...
Page 7 needs OCR...
Page 8 needs OCR...
Page 9 needs OCR...
Page 10 needs OCR...
Page 11 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Page 14 needs OCR...
Page 15 needs OCR...
Page 16 needs OCR...
Page 17 needs OCR...
Page 18 needs OCR...
Page 19 needs OCR...
Page 20 needs OCR...
Page 21 needs OCR...
Page 22 needs OCR...
Page 23 needs OCR...
Page 24 needs OCR...
Page 25 needs OCR...
Page 26 needs OCR...
Page 27 needs OCR...
Page 28 needs OCR...
Page 29 needs OCR...
Page 30 needs OCR...
Page 31 needs OCR...
Page 32 needs OCR...
Page 33 needs OCR...
Page 34 needs OCR...
Page 35 needs OCR...
Page 36 needs OCR...
Page 37 needs OCR...
Page 38 needs OCR...
Page 39 needs OCR...
Page 40 needs OCR...
Page 41 needs OCR...
Page 42 needs OCR...
Page 43 needs OCR...
Page 44 needs OCR...
Page 45 needs OCR...
Page 46 needs OCR...
Page 47 needs OCR...
Page 48 needs OCR...
Page 49 needs OCR...
Page 50 needs OCR...
Page 51 needs OCR...
Page 52 needs OCR...
Page 53 needs OCR...
Page 54 needs OCR...
Page 55 needs OCR...
Page 56 needs OCR...
Page 57 needs OCR...
Page 58 needs OCR...
Fetching https://api.pmg.org.za/bill/1237/
Page 8 needs OCR...
Page 9 needs OCR...
Page 10 needs OCR...
Page 11 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Page 14 needs OCR...
Page 15 needs OCR...
Page 16 needs OCR...
Page 17 needs OCR...
Page 18 needs OCR...
Page 19 needs OCR...
Page 20 needs OCR...
Page 21 needs OCR...
Page 22 needs OCR...
Page 23 needs OCR...
Page 24 needs OCR...
Page 25 needs OCR...
Page 26 needs OCR...
Page 27 needs OCR...
Page 28 needs OCR...
Page 29 needs OCR...
Page 30 needs OCR...
Page 31 needs OCR...
Page 32 needs OCR...
Page 33 needs OCR...
Page 34 needs OCR...
Page 35 needs OCR...
Page 36 needs OCR...
Page 37 needs OCR...
Fetching https://api.pmg.org.za/bill/1238/
Fetching https://api.pmg.org.za/bill/1239/
Fetching https://api.pmg.org.za/bill/1240/
Fetching https://api.pmg.org.za/bill/1241/
Page 4 needs OCR...
Page 5 needs OCR...
Fetching https://api.pmg.org.za/bill/1242/
Fetching https://api.pmg.org.za/bill/1243/
Fetching https://api.pmg.org.za/bill/1244/
Page 12 needs OCR...
Page 22 needs OCR...
Page 26 needs OCR...
Fetching https://api.pmg.org.za/bill/1245/
Fetching https://api.pmg.org.za/bill/1246/
Fetching https://api.pmg.org.za/bill/1247/
Fetching https://api.pmg.org.za/bill/1248/
Fetching https://api.pmg.org.za/bill/1249/
Page 1 needs OCR...
Page 2 needs OCR...
Page 3 needs OCR...
Page 4 needs OCR...
Page 5 needs OCR...
Page 6 needs OCR...
Page 7 needs OCR...
Page 8 needs OCR...
Page 9 needs OCR...
Page 10 needs OCR...
Page 11 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Page 14 needs OCR...
Page 15 needs OCR...
Page 16 needs OCR...
Page 17 needs OCR...
Page 18 needs OCR...
Page 19 needs OCR...
Page 20 needs OCR...
Page 21 needs OCR...
Page 22 needs OCR...
Page 23 needs OCR...
Page 24 needs OCR...
Page 25 needs OCR...
Page 26 needs OCR...
Page 27 needs OCR...
Page 28 needs OCR...
Page 29 needs OCR...
Fetching https://api.pmg.org.za/bill/1250/
Fetching https://api.pmg.org.za/bill/1251/
Fetching https://api.pmg.org.za/bill/1252/
Fetching https://api.pmg.org.za/bill/1253/
Fetching https://api.pmg.org.za/bill/1254/
Fetching https://api.pmg.org.za/bill/1255/
Fetching https://api.pmg.org.za/bill/1256/
HTTP error for Bill ID 1256: Client error '404 Not Found' for url 'https://api.pmg.org.za/bill/1256/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Fetching https://api.pmg.org.za/bill/1257/
HTTP error for Bill ID 1257: Client error '404 Not Found' for url 'https://api.pmg.org.za/bill/1257/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Fetching https://api.pmg.org.za/bill/1258/
HTTP error for Bill ID 1258: Client error '404 Not Found' for url 'https://api.pmg.org.za/bill/1258/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Fetching https://api.pmg.org.za/bill/1259/
HTTP error for Bill ID 1259: Client error '404 Not Found' for url 'https://api.pmg.org.za/bill/1259/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Fetching https://api.pmg.org.za/bill/1260/
HTTP error for Bill ID 1260: Client error '404 Not Found' for url 'https://api.pmg.org.za/bill/1260/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Fetching https://api.pmg.org.za/bill/1261/
Fetching https://api.pmg.org.za/bill/1262/
Page 6 needs OCR...
Page 7 needs OCR...
Fetching https://api.pmg.org.za/bill/1263/
Page 4 needs OCR...
Page 5 needs OCR...
Page 6 needs OCR...
Page 7 needs OCR...
Fetching https://api.pmg.org.za/bill/1264/
Fetching https://api.pmg.org.za/bill/1265/
Page 6 needs OCR...
Page 7 needs OCR...
Fetching https://api.pmg.org.za/bill/1266/
Fetching https://api.pmg.org.za/bill/1267/
Page 60 needs OCR...
Page 61 needs OCR...
Page 62 needs OCR...
Page 63 needs OCR...
Page 64 needs OCR...
Page 65 needs OCR...
Page 66 needs OCR...
Page 67 needs OCR...
Page 68 needs OCR...
Page 69 needs OCR...
Page 70 needs OCR...
Page 71 needs OCR...
Page 72 needs OCR...
Page 73 needs OCR...
Page 74 needs OCR...
Page 75 needs OCR...
Page 76 needs OCR...
Page 77 needs OCR...
Page 78 needs OCR...
Page 79 needs OCR...
Page 80 needs OCR...
Page 81 needs OCR...
Page 82 needs OCR...
Page 83 needs OCR...
Page 84 needs OCR...
Page 85 needs OCR...
Page 86 needs OCR...
Page 87 needs OCR...
Page 88 needs OCR...
Page 89 needs OCR...
Page 90 needs OCR...
Page 91 needs OCR...
Page 92 needs OCR...
Page 93 needs OCR...
Page 94 needs OCR...
Page 95 needs OCR...
Page 96 needs OCR...
Page 97 needs OCR...
Page 98 needs OCR...
Page 99 needs OCR...
Page 100 needs OCR...
Page 101 needs OCR...
Page 102 needs OCR...
Page 103 needs OCR...
Page 104 needs OCR...
Page 105 needs OCR...
Page 106 needs OCR...
Page 107 needs OCR...
Page 108 needs OCR...
Page 109 needs OCR...
Page 110 needs OCR...
Page 111 needs OCR...
Page 112 needs OCR...
Page 113 needs OCR...
Page 114 needs OCR...
Page 115 needs OCR...
Page 116 needs OCR...
Page 117 needs OCR...
Page 118 needs OCR...
Page 119 needs OCR...
Page 120 needs OCR...
Page 121 needs OCR...
Page 122 needs OCR...
Page 123 needs OCR...
Page 124 needs OCR...
Page 125 needs OCR...
Page 126 needs OCR...
Page 127 needs OCR...
Page 128 needs OCR...
Page 129 needs OCR...
Page 130 needs OCR...
Page 131 needs OCR...
Page 132 needs OCR...
Page 133 needs OCR...
Page 134 needs OCR...
Page 135 needs OCR...
Page 136 needs OCR...
Page 137 needs OCR...
Page 138 needs OCR...
Page 139 needs OCR...
Page 140 needs OCR...
Page 141 needs OCR...
Page 142 needs OCR...
Page 143 needs OCR...
Page 144 needs OCR...
Page 145 needs OCR...
Page 146 needs OCR...
Page 147 needs OCR...
Page 148 needs OCR...
Page 149 needs OCR...
Page 150 needs OCR...
Page 151 needs OCR...
Page 152 needs OCR...
Page 153 needs OCR...
Page 154 needs OCR...
Page 155 needs OCR...
Page 156 needs OCR...
Page 157 needs OCR...
Page 158 needs OCR...
Page 159 needs OCR...
Page 160 needs OCR...
Page 161 needs OCR...
Page 162 needs OCR...
Page 163 needs OCR...
Page 164 needs OCR...
Page 165 needs OCR...
Page 166 needs OCR...
Page 167 needs OCR...
Page 168 needs OCR...
Page 169 needs OCR...
Page 170 needs OCR...
Page 171 needs OCR...
Page 172 needs OCR...
Page 173 needs OCR...
Page 174 needs OCR...
Page 175 needs OCR...
Page 176 needs OCR...
Page 177 needs OCR...
Page 178 needs OCR...
Page 179 needs OCR...
Page 180 needs OCR...
Page 181 needs OCR...
Page 182 needs OCR...
Page 183 needs OCR...
Page 184 needs OCR...
Page 185 needs OCR...
Page 186 needs OCR...
Page 187 needs OCR...
Page 188 needs OCR...
Page 189 needs OCR...
Page 190 needs OCR...
Page 191 needs OCR...
Page 192 needs OCR...
Page 193 needs OCR...
Page 194 needs OCR...
Page 195 needs OCR...
Page 196 needs OCR...
Page 197 needs OCR...
Page 198 needs OCR...
Page 199 needs OCR...
Page 200 needs OCR...
Page 201 needs OCR...
Page 202 needs OCR...
Page 203 needs OCR...
Page 204 needs OCR...
Page 205 needs OCR...
Page 206 needs OCR...
Page 207 needs OCR...
Page 208 needs OCR...
Page 209 needs OCR...
Page 210 needs OCR...
Page 211 needs OCR...
Page 212 needs OCR...
Page 213 needs OCR...
Page 214 needs OCR...
Page 215 needs OCR...
Page 216 needs OCR...
Page 217 needs OCR...
Page 218 needs OCR...
Page 219 needs OCR...
Page 220 needs OCR...
Page 221 needs OCR...
Page 222 needs OCR...
Page 223 needs OCR...
Page 224 needs OCR...
Page 225 needs OCR...
Page 226 needs OCR...
Page 227 needs OCR...
Page 228 needs OCR...
Page 229 needs OCR...
Page 230 needs OCR...
Page 231 needs OCR...
Page 232 needs OCR...
Page 233 needs OCR...
Page 234 needs OCR...
Page 235 needs OCR...
Page 236 needs OCR...
Page 237 needs OCR...
Page 238 needs OCR...
Page 239 needs OCR...
Page 240 needs OCR...
Page 241 needs OCR...
Page 242 needs OCR...
Page 243 needs OCR...
Page 244 needs OCR...
Page 245 needs OCR...
Page 246 needs OCR...
Page 247 needs OCR...
Page 248 needs OCR...
Page 249 needs OCR...
Page 250 needs OCR...
Page 251 needs OCR...
Page 252 needs OCR...
Page 253 needs OCR...
Page 254 needs OCR...
Page 255 needs OCR...
Page 256 needs OCR...
Page 257 needs OCR...
Fetching https://api.pmg.org.za/bill/1268/
Page 14 needs OCR...
Page 15 needs OCR...
Fetching https://api.pmg.org.za/bill/1269/
Fetching https://api.pmg.org.za/bill/1270/
Page 7 needs OCR...
Fetching https://api.pmg.org.za/bill/1271/
Page 2 needs OCR...
Fetching https://api.pmg.org.za/bill/1272/
Page 18 needs OCR...
Page 19 needs OCR...
Fetching https://api.pmg.org.za/bill/1273/
Page 6 needs OCR...
Page 7 needs OCR...
Fetching https://api.pmg.org.za/bill/1274/
Fetching https://api.pmg.org.za/bill/1275/
Fetching https://api.pmg.org.za/bill/1276/
Fetching https://api.pmg.org.za/bill/1277/
Fetching https://api.pmg.org.za/bill/1278/
HTTP error for Bill ID 1278: Client error '404 Not Found' for url 'https://api.pmg.org.za/bill/1278/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Fetching https://api.pmg.org.za/bill/1279/
Fetching https://api.pmg.org.za/bill/1280/
Page 54 needs OCR...
Page 55 needs OCR...
Page 56 needs OCR...
Page 60 needs OCR...
Page 61 needs OCR...
Page 64 needs OCR...
Page 65 needs OCR...
Page 67 needs OCR...
Page 68 needs OCR...
Page 75 needs OCR...
Page 83 needs OCR...
Page 86 needs OCR...
Page 87 needs OCR...
Page 89 needs OCR...
Page 91 needs OCR...
Page 92 needs OCR...
Page 94 needs OCR...
Page 95 needs OCR...
Page 96 needs OCR...
Page 97 needs OCR...
Page 100 needs OCR...
Page 101 needs OCR...
Page 103 needs OCR...
Page 107 needs OCR...
Page 113 needs OCR...
Page 120 needs OCR...
Page 123 needs OCR...
Page 126 needs OCR...
Page 127 needs OCR...
Page 128 needs OCR...
Page 129 needs OCR...
Page 130 needs OCR...
Page 131 needs OCR...
Page 132 needs OCR...
Page 133 needs OCR...
Page 134 needs OCR...
Page 135 needs OCR...
Page 136 needs OCR...
Page 137 needs OCR...
Page 138 needs OCR...
Page 139 needs OCR...
Page 140 needs OCR...
Page 141 needs OCR...
Page 142 needs OCR...
Page 143 needs OCR...
Page 144 needs OCR...
Page 145 needs OCR...
Page 146 needs OCR...
Page 147 needs OCR...
Page 148 needs OCR...
Page 149 needs OCR...
Page 150 needs OCR...
Page 151 needs OCR...
Page 152 needs OCR...
Page 153 needs OCR...
Page 154 needs OCR...
Page 155 needs OCR...
Page 156 needs OCR...
Page 157 needs OCR...
Page 158 needs OCR...
Page 159 needs OCR...
Page 160 needs OCR...
Page 161 needs OCR...
Page 162 needs OCR...
Page 163 needs OCR...
Page 164 needs OCR...
Page 165 needs OCR...
Page 166 needs OCR...
Page 167 needs OCR...
Page 168 needs OCR...
Page 169 needs OCR...
Page 170 needs OCR...
Page 171 needs OCR...
Page 172 needs OCR...
Page 173 needs OCR...
Page 174 needs OCR...
Page 175 needs OCR...
Page 176 needs OCR...
Page 177 needs OCR...
Page 178 needs OCR...
Page 179 needs OCR...
Page 180 needs OCR...
Page 181 needs OCR...
Page 182 needs OCR...
Page 183 needs OCR...
Page 184 needs OCR...
Page 185 needs OCR...
Page 186 needs OCR...
Page 187 needs OCR...
Page 188 needs OCR...
Page 189 needs OCR...
Page 190 needs OCR...
Page 191 needs OCR...
Page 192 needs OCR...
Page 193 needs OCR...
Page 194 needs OCR...
Page 195 needs OCR...
Page 196 needs OCR...
Page 197 needs OCR...
Page 198 needs OCR...
Page 199 needs OCR...
Page 200 needs OCR...
Page 201 needs OCR...
Page 202 needs OCR...
Page 203 needs OCR...
Page 204 needs OCR...
Page 205 needs OCR...
Page 206 needs OCR...
Page 207 needs OCR...
Page 208 needs OCR...
Page 209 needs OCR...
Page 210 needs OCR...
Page 211 needs OCR...
Page 212 needs OCR...
Page 213 needs OCR...
Page 214 needs OCR...
Page 215 needs OCR...
Page 216 needs OCR...
Page 217 needs OCR...
Page 218 needs OCR...
Page 219 needs OCR...
Page 220 needs OCR...
Page 221 needs OCR...
Page 222 needs OCR...
Page 223 needs OCR...
Page 224 needs OCR...
Page 225 needs OCR...
Page 226 needs OCR...
Page 227 needs OCR...
Page 228 needs OCR...
Page 229 needs OCR...
Page 230 needs OCR...
Page 231 needs OCR...
Page 232 needs OCR...
Page 233 needs OCR...
Page 234 needs OCR...
Page 235 needs OCR...
Page 236 needs OCR...
Page 237 needs OCR...
Page 238 needs OCR...
Page 239 needs OCR...
Page 240 needs OCR...
Page 241 needs OCR...
Page 242 needs OCR...
Page 243 needs OCR...
Page 244 needs OCR...
Page 245 needs OCR...
Page 246 needs OCR...
Page 247 needs OCR...
Page 248 needs OCR...
Page 249 needs OCR...
Page 250 needs OCR...
Page 251 needs OCR...
Page 252 needs OCR...
Page 253 needs OCR...
Page 254 needs OCR...
Page 255 needs OCR...
Page 256 needs OCR...
Page 257 needs OCR...
Fetching https://api.pmg.org.za/bill/1281/
Fetching https://api.pmg.org.za/bill/1282/
Fetching https://api.pmg.org.za/bill/1283/
Fetching https://api.pmg.org.za/bill/1284/
Fetching https://api.pmg.org.za/bill/1285/
Fetching https://api.pmg.org.za/bill/1286/
Fetching https://api.pmg.org.za/bill/1287/
Fetching https://api.pmg.org.za/bill/1288/
Fetching https://api.pmg.org.za/bill/1289/
Page 14 needs OCR...
Page 15 needs OCR...
Fetching https://api.pmg.org.za/bill/1290/
HTTP error for Bill ID 1290: Client error '404 Not Found' for url 'https://api.pmg.org.za/bill/1290/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Fetching https://api.pmg.org.za/bill/1291/
HTTP error for Bill ID 1291: Client error '404 Not Found' for url 'https://api.pmg.org.za/bill/1291/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Fetching https://api.pmg.org.za/bill/1292/
Fetching https://api.pmg.org.za/bill/1293/
Fetching https://api.pmg.org.za/bill/1294/
Page 1 needs OCR...
Page 2 needs OCR...
Page 3 needs OCR...
Page 4 needs OCR...
Page 5 needs OCR...
Page 6 needs OCR...
Page 7 needs OCR...
Page 8 needs OCR...
Page 9 needs OCR...
Page 10 needs OCR...
Page 11 needs OCR...
Page 12 needs OCR...
Page 13 needs OCR...
Page 14 needs OCR...
Page 15 needs OCR...
Page 16 needs OCR...
Page 17 needs OCR...
Page 18 needs OCR...
Page 19 needs OCR...
Page 20 needs OCR...
Page 21 needs OCR...
Page 22 needs OCR...
Page 23 needs OCR...
Page 24 needs OCR...
Page 25 needs OCR...
Page 26 needs OCR...
Page 27 needs OCR...
Page 28 needs OCR...
Page 29 needs OCR...
Page 30 needs OCR...
Page 31 needs OCR...
Page 32 needs OCR...
Page 33 needs OCR...
Page 34 needs OCR...
Page 35 needs OCR...
Page 36 needs OCR...
Page 37 needs OCR...
Page 38 needs OCR...
Page 39 needs OCR...
Page 40 needs OCR...
Page 41 needs OCR...
Page 42 needs OCR...
Page 43 needs OCR...
Page 44 needs OCR...
Page 45 needs OCR...
Page 46 needs OCR...
Page 47 needs OCR...
Page 48 needs OCR...
Page 49 needs OCR...
Page 50 needs OCR...
Page 51 needs OCR...
Page 52 needs OCR...
Page 53 needs OCR...
Page 54 needs OCR...
Page 55 needs OCR...
Page 56 needs OCR...
Page 57 needs OCR...
Page 58 needs OCR...
Page 59 needs OCR...
Page 60 needs OCR...
Page 61 needs OCR...
Page 62 needs OCR...
Page 63 needs OCR...
Page 64 needs OCR...
Page 65 needs OCR...
Page 66 needs OCR...
Page 67 needs OCR...
Page 68 needs OCR...
Page 69 needs OCR...
Page 70 needs OCR...
Page 71 needs OCR...
Page 72 needs OCR...
Page 73 needs OCR...
Page 74 needs OCR...
Page 75 needs OCR...
Page 76 needs OCR...
Page 77 needs OCR...
Page 78 needs OCR...
Page 79 needs OCR...
Page 80 needs OCR...
Page 81 needs OCR...
Page 82 needs OCR...
Page 83 needs OCR...
Page 84 needs OCR...
Page 85 needs OCR...
Page 86 needs OCR...
Fetching https://api.pmg.org.za/bill/1295/
Fetching https://api.pmg.org.za/bill/1296/
Page 6 needs OCR...
Page 7 needs OCR...
Fetching https://api.pmg.org.za/bill/1297/
Page 4 needs OCR...
Fetching https://api.pmg.org.za/bill/1298/

## Show loaded data

In [ ]:
rows = bill_table.scan().to_pandas()
rows

,bill_identifier,title,bill_number,year,act_name,introduced_by,date_of_introduction,date_of_assent,effective_date,status_name,type_name,events_json,pdf_url,pdf_text
0,1208,National State Enterprises Bill,1.0,2024,None,Minister of Public Enterprises,2024-01-24,None,None,na,S75,"[{""created_at"": ""2025-07-09T09:28:22.961073+00...",https://pmg.org.za/files/B1-2024_National_Stat...,REPUBLIC OF SOUTH AFRICA\nNATIONAL STATE\nENTE...
1,1209,Repeal of South African Airways Bill,2.0,2024,None,Minister of Public Enterprises,2024-01-24,None,None,withdrawn,S75,"[{""created_at"": ""2024-01-25T05:37:26.481342+00...",https://pmg.org.za/files/B2-2024_Repeal_of_Sou...,REPUBLIC OF SOUTH AFRICA\nREPEAL OF\nSOUTH AFR...
2,1210,Pension Funds Amendment Bill,3.0,2024,Act 31 of 2024,Minister of Finance,2024-01-30,2024-07-18,2024-08-23,act-commenced,S75,"[{""created_at"": ""2024-01-31T11:28:51.693116+00...",https://pmg.org.za/files/50968_23-7_PensionsFu...,cure\nthe \nis \nPrevention \n0800-0123-22 \nH...
3,1211,Division of Revenue Bill,4.0,2024,Act 24 of 2024,Minister of Finance,2024-02-21,2024-06-03,2024-06-03,act-commenced,S76,"[{""created_at"": ""2024-02-21T09:25:57.278369+00...",https://pmg.org.za/files/50743_03-06_Divisiono...,cure\nthe \nis \nPrevention \n0800-0123-22 \nH...
4,1212,Appropriation Bill,5.0,2024,Act 40 of 2024,Minister of Finance,2024-02-21,2024-08-16,2024-08-16,act-commenced,S77,"[{""created_at"": ""2024-02-21T09:27:30.224460+00...",https://pmg.org.za/files/51101_ApproprriationA...,cure\nthe \nis \nPrevention \n0800-0123-22 \nH...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,1331,Traditional and Khoi-San Leadership Bill,NaN,2026,None,Minister of Cooperative Governance and Traditi...,2026-02-27,None,None,None,Draft,[],None,
113,1332,Gas Bill,6.0,2026,None,Minister of Electricity and Energy,2026-03-05,None,None,na,S76,"[{""created_at"": ""2026-03-06T10:03:22.548451+00...",https://pmg.org.za/files/B6-2026_Gas.pdf,REPUBLIC OF SOUTH AFRICA\nGAS BILL\n(As introd...
114,1333,Gas Bill,NaN,2026,None,Minister of Electricity and Energy,None,None,None,None,Draft,[],None,
115,1334,South African Geographical Names Council Amend...,NaN,2026,None,"Minister of Sport, Arts and Culture",2026-03-06,None,None,None,Draft,[],https://pmg.org.za/files/260306South_African_G...,\n \n \nREPUBLIC OF SOUTH AFRICA \n \n \n \n ...
116,1335,Public Procurement Amendment Bill,7.0,2026,None,"Mr MJ Cuthbert, MP",2026-03-12,None,None,na,Private Member Bill: S76,"[{""created_at"": ""2026-03-12T15:49:11.171740+00...",https://pmg.org.za/files/B7-2026_Public_Procur...,REPUBLIC OF SOUTH AFRICA\nPUBLIC PROCUREMENT\n...

## List stored PDFs

In [ ]:
print("Files currently in bills folder:")

response = s3_client.list_objects_v2(
    Bucket=bucket_name,
    Prefix="bills/"
)

for obj in response.get("Contents", []):
    print(obj["Key"])

Files currently in bills folder:
bills/1208.pdf
bills/1209.pdf
bills/1210.pdf
bills/1211.pdf
bills/1212.pdf
bills/1213.pdf
bills/1214.pdf
bills/1215.pdf
bills/1216.pdf
bills/1217.pdf
bills/1218.pdf
bills/1219.pdf
bills/1220.pdf
bills/1221.pdf
bills/1222.pdf
bills/1223.pdf
bills/1224.pdf
bills/1225.pdf
bills/1226.pdf
bills/1227.pdf
bills/1228.pdf
bills/1229.pdf
bills/1230.pdf
bills/1231.pdf
bills/1232.pdf
bills/1233.pdf
bills/1234.pdf
bills/1235.pdf
bills/1236.pdf
bills/1237.pdf
bills/1238.pdf
bills/1239.pdf
bills/1240.pdf
bills/1241.pdf
bills/1242.pdf
bills/1243.pdf
bills/1244.pdf
bills/1245.pdf
bills/1246.pdf
bills/1247.pdf
bills/1248.pdf
bills/1249.pdf
bills/1250.pdf
bills/1251.pdf
bills/1252.pdf
bills/1253.pdf
bills/1254.pdf
bills/1255.pdf
bills/1261.pdf
bills/1262.pdf
bills/1263.pdf
bills/1264.pdf
bills/1265.pdf
bills/1266.pdf
bills/1267.pdf
bills/1268.pdf
bills/1269.pdf
bills/1270.pdf
bills/1271.pdf
bills/1272.pdf
bills/1273.pdf
bills/1274.pdf
bills/1275.pdf
bills/1276.pdf
bills/1277.pdf
bills/1279.pdf
bills/1280.pdf
bills/1281.pdf
bills/1282.pdf
bills/1283.pdf
bills/1284.pdf
bills/1285.pdf
bills/1286.pdf
bills/1287.pdf
bills/1288.pdf
bills/1289.pdf
bills/1292.pdf
bills/1293.pdf
bills/1294.pdf
bills/1295.pdf
bills/1296.pdf
bills/1297.pdf
bills/1298.pdf
bills/1299.pdf
bills/1300.pdf
bills/1301.pdf
bills/1302.pdf
bills/1303.pdf
bills/1304.pdf
bills/1305.pdf
bills/1306.pdf
bills/1308.pdf
bills/1309.pdf
bills/1310.pdf
bills/1311.pdf
bills/1312.pdf
bills/1313.pdf
bills/1314.pdf
bills/1315.pdf
bills/1316.pdf
bills/1317.pdf
bills/1318.pdf
bills/1319.pdf
bills/1320.pdf
bills/1321.pdf
bills/1322.pdf
bills/1325.pdf
bills/1326.pdf
bills/1327.pdf
bills/1328.pdf
bills/1330.pdf
bills/1332.pdf
bills/1334.pdf
bills/1335.pdf